/* 정적 프로토타입 전용. 네트워크/API/DB 연결 없이 아래 더미 데이터만 사용합니다. */
const DEMO = {
  admin: { id: 'admin', password: 'admin1234', name: '관리자', role: '시스템 관리자' },
  kpi: [{label:'오늘 생산량',value:'12,480',unit:'EA',note:'전일 대비 +4.8%'},{label:'종합 수율',value:'98.2',unit:'%',note:'목표 대비 +0.7% '},{label:'불량 건수',value:'23',unit:'건',note:'전일 대비 -12.5%',warn:true},{label:'가동 설비',value:'18 / 20',unit:'대',note:'가동률 90.0%'}],
  alerts: [{title:'프레스 3호기 진동 수치 상승',time:'10분 전',level:'주의'},{title:'AOI 2라인 반복 불량 감지',time:'34분 전',level:'확인 필요'},{title:'출하 검사 완료',time:'1시간 전',level:'정상'}],
  reports: [{title:'실적 집계·조회',desc:'기간별 생산 실적과 목표 달성률을 확인합니다.',icon:'▦'},{title:'불량 현황 조회',desc:'공정·모델별 불량 추이와 Pareto를 확인합니다.',icon:'◒'},{title:'AOI 판정 분석·예측',desc:'이미지 판정 결과와 AI 예측 근거를 확인합니다.',icon:'⌁'},{title:'일일 생산현황 보고',desc:'일일 생산 현황을 문서 형식으로 조회합니다.',icon:'▤'},{title:'출하 계획 보고서',desc:'고객사별 출하 계획과 진행 상태를 확인합니다.',icon:'↗'},{title:'스크랩 보고서',desc:'스크랩 원인과 비용을 분석합니다.',icon:'◌'}]
};
let state = { loggedIn: false, page: 'ai' };
const $ = (s, root=document) => root.querySelector(s);
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function login(){
  document.querySelector('#app').innerHTML=`<main class="login-page"><section class="login-card"><div class="login-visual"><div class="constellation">${Array.from({length:12},(_,i)=>`<i class="triangle" aria-hidden="true"></i>`).join('')}</div><div class="brand" style="position:relative;z-index:1"><span class="brand-mark">D</span><div><strong>덕우전자 AX</strong><small>AI DECISION LAYER</small></div></div><h1 style="position:relative;z-index:1">현장의 답은<br><span style="color:var(--blue)">이미 데이터 안에 있습니다.</span></h1><p style="position:relative;z-index:1">MES 위에 얹은 AI 계층이 생산·품질·설비 데이터를 읽고, 질의하면 근거와 함께 답합니다. 보고서는 스스로 정리되고, 이상은 먼저 알려 드립니다.</p><small style="position:absolute;bottom:28px;color:var(--muted);font-size:10px;z-index:1">© DERKWOO ELECTRONICS CO., LTD. · On-premise AI</small></div><form class="login-form" id="login-form"><h2>로그인</h2><p>사내 사번과 비밀번호로 접속합니다.</p><div class="field"><label for="id">사번</label><input id="id" placeholder="예) 10004" autocomplete="username"></div><div class="field"><label for="password">비밀번호</label><input id="password" type="password" placeholder="비밀번호" autocomplete="current-password"></div><button class="primary" style="width:100%">로그인</button><button type="button" class="demo-login" id="demo-admin">▣ 관리자 더미 계정으로 바로 시작</button><p class="login-note">프로토타입에서는 인증 서버에 연결하지 않습니다.<br>관리자 버튼을 누르면 데모 계정으로 즉시 입장합니다.</p></form></section></main>`;
  $('#login-form').addEventListener('submit',e=>{e.preventDefault(); const id=$('#id').value; if(id===DEMO.admin.id || id==='10004') enter(); else toast('프로토타입에서는 관리자 더미 계정만 사용할 수 있습니다.');});
  $('#demo-admin').addEventListener('click',enter);
}
function enter(){state.loggedIn=true; render(); toast('관리자 더미 계정으로 입장했습니다.');}
function toast(msg){const old=$('.toast'); if(old)old.remove(); const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
function layout(content){return `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">D</span><div><strong>덕우전자 AX</strong><small>AI DECISION LAYER</small></div></div><div><p class="nav-label">MENU</p><nav class="nav"><button data-page="ai" class="${state.page==='ai'?'active':''}"><span class="dot">⌁</span>자연어 질의</button><button data-page="dashboard" class="${state.page==='dashboard'?'active':''}"><span class="dot">▦</span>대시보드 <span class="nav-count">3　⌄</span></button><button data-page="operation" class="${state.page==='operation'?'active':''}"><span class="dot">⌁</span>생산 및 품질 관리 <span class="nav-count">3　⌄</span></button><button data-page="reports" class="${state.page==='reports'?'active':''}"><span class="dot">▤</span>보고서</button><button data-page="system" class="${state.page==='system'?'active':''}"><span class="dot">⚙</span>시스템관리 <span class="nav-count">15　⌃</span></button></nav><div class="subnav">${['계정 관리','메뉴 접근 권한','데이터 접근 권한','이상 알림 발송 조건 관리','알림 수신자 관리','용어 사전 관리','제품군 순위 관리','자연어 질의 이력','보안 감사 로그','AI 모델 설정','AI 모델 버전 관리','Agent 실행 현황','지표 측정 데이터 관리','보고서 다운로드 이력','데이터 연동 이력'].map((x,i)=>`<button class="${state.page==='system'&&i===5?'active':''}" data-page="system">${i===5?'• ':''}${x}</button>`).join('')}</div></div><div class="sidebar-footer">정적 프로토타입<br>데이터 기준일 · 2026.09.09</div></aside><main class="main"><header class="topbar"><div class="crumb"><button class="ghost mobile-menu">☰</button><span>시스템관리 / </span><strong>${pageName()}</strong></div><div class="top-actions"><button class="primary" data-page="ai">✦ AI 질의</button><button class="icon-btn" title="알림">♢<span class="badge">3</span></button><div class="user"><div class="avatar">관</div><span>관리자<br><small style="color:var(--muted)">통합관리자</small></span></div><button class="ghost" id="logout">⌄</button></div></header><section class="page">${content}</section></main></div>`}
function pageName(){return ({ai:'AI 질의 홈',dashboard:'생산 모니터링',operation:'생산 및 품질 관리',reports:'보고서',system:'시스템 관리'})[state.page]}
function home(){return `<div class="eyebrow">AI DECISION SUPPORT</div><h1 class="page-title">오늘의 업무를 물어보세요.</h1><p class="page-subtitle">생산·품질 데이터를 바탕으로 현황을 요약하고 다음 액션을 제안합니다.</p><div class="chat-card"><div class="chat-content"><p class="greeting">관리자님, 좋은 아침입니다.</p><h2 class="chat-title">지금 현장에서 <em>무슨 일이</em><br>일어나고 있나요?</h2><div class="briefing"><div><span>종합 수율</span><b>98.2%</b><small class="kpi-note">▲ 0.7%</small></div><div><span>생산 현황</span><b>12,480 EA</b><small class="kpi-note">목표 96%</small></div><div><span>현재 이슈</span><b>3건</b><small class="kpi-note warn">확인 필요</small></div></div><form class="prompt" id="ask-form"><input id="ask" placeholder="예: 오늘 불량률이 높은 공정과 원인을 알려줘"><button class="primary">질의하기</button></form><div class="ai-response" id="response">오늘 불량률은 <b>0.18%</b>로 전일 대비 12.5% 개선되었습니다. 다만 <b>프레스 3호기</b>에서 진동 수치가 상승하고 있어, 금형 교체 이력과 소재 LOT를 우선 확인하는 것을 권장합니다.</div></div></div>`}
function dashboard(){let bars=[82,70,90,64,76,88,94,78,86,92,84,97];return `<div class="eyebrow">PRODUCTION MONITORING</div><h1 class="page-title">생산 모니터링</h1><p class="page-subtitle">주요 생산 지표와 라인별 상태를 실시간에 가깝게 확인하는 화면입니다.</p><div class="grid kpis">${DEMO.kpi.map(k=>`<div class="card"><div class="kpi-label">${k.label}</div><div class="kpi-value">${k.value}<small style="font-size:12px;margin-left:4px;color:var(--muted)">${k.unit}</small></div><div class="kpi-note ${k.warn?'warn':''}">${k.note}</div></div>`).join('')}</div><div class="two-col"><div class="card"><div class="section-head"><h3>시간대별 생산 실적</h3><span>오늘 · 08:00–19:00</span></div><div class="chart">${bars.map((v,i)=>`<div class="bar-wrap"><div class="bar ${i%4===2?'amber':''}" style="height:${v}%"></div><span class="bar-label">${String(i+8).padStart(2,'0')}</span></div>`).join('')}</div></div><div class="card"><div class="section-head"><h3>현재 알림</h3><span>전체 보기 →</span></div><table class="table"><tbody>${DEMO.alerts.map(a=>`<tr><td><span class="status ${a.level==='주의'?'warn':a.level==='확인 필요'?'danger':''}">${a.level}</span><br><b style="font-size:11px;line-height:2">${a.title}</b><br><span style="color:var(--muted);font-size:10px">${a.time}</span></td></tr>`).join('')}</tbody></table></div></div>`}
function operation(){return `<div class="eyebrow">OPERATION & QUALITY</div><h1 class="page-title">생산 및 품질 관리</h1><p class="page-subtitle">생산 실적, 불량 현황, AOI 판정 결과를 업무 흐름에 맞게 조회합니다.</p><div class="report-grid"><div class="card report-card"><div><div style="font-size:24px;color:var(--blue)">▦</div><h3>실적 집계·조회</h3><p>라인·모델·기간별 생산 실적과 목표 달성률</p></div><button data-toast="실적 집계 화면을 열었습니다.">화면 열기 →</button></div><div class="card report-card"><div><div style="font-size:24px;color:var(--red)">◒</div><h3>불량 현황 조회</h3><p>공정별 불량률과 원인 Pareto를 한눈에</p></div><button data-toast="불량 현황 화면을 열었습니다.">화면 열기 →</button></div><div class="card report-card"><div><div style="font-size:24px;color:var(--green)">⌁</div><h3>AOI 판정 분석·예측</h3><p>AI 판정 결과와 근거 이미지, 예측 추이</p></div><button data-toast="AOI 판정 분석 화면을 열었습니다.">화면 열기 →</button></div></div><div class="two-col"><div class="card"><div class="section-head"><h3>라인별 품질 현황</h3><span>기준일 2026.09.09</span></div><table class="table"><thead><tr><th>라인</th><th>생산량</th><th>불량률</th><th>상태</th></tr></thead><tbody>${[['1라인','4,240','0.12%','정상'],['2라인','3,810','0.21%','주의'],['3라인','4,430','0.16%','정상']].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]} EA</td><td>${r[2]}</td><td><span class="status ${r[3]==='주의'?'warn':''}">${r[3]}</span></td></tr>`).join('')}</tbody></table></div><div class="card soft"><div class="section-head"><h3>AI 추천 액션</h3><span>우선순위 1</span></div><p style="font-size:13px;line-height:1.7;margin:0">2라인 AOI 불량 중 <b>납땜 부족</b> 유형이 41%를 차지합니다. 최근 교대 이후 설정값 변경 여부를 확인하세요.</p><button class="primary" style="margin-top:18px" data-toast="추천 액션을 작업 메모에 저장했습니다.">액션 저장</button></div></div>`}
function reports(){return `<div class="eyebrow">REPORT CENTER</div><h1 class="page-title">보고서</h1><p class="page-subtitle">업무 목적에 맞는 보고서를 선택해 더미 데이터로 미리 확인합니다.</p><div class="notice">프로토타입 안내 · 아래 보고서는 화면 구조와 사용 흐름을 확인하기 위한 샘플입니다. 실제 API 또는 DB를 호출하지 않습니다.</div><div class="report-grid">${DEMO.reports.map(r=>`<div class="card report-card"><div><div style="font-size:24px;color:var(--blue)">${r.icon}</div><h3>${r.title}</h3><p>${r.desc}</p></div><button data-toast="${r.title} 미리보기를 열었습니다.">미리보기 →</button></div>`).join('')}</div>`}
function system(){return `<div class="eyebrow">SYSTEM ADMINISTRATION</div><h1 class="page-title">시스템 관리</h1><p class="page-subtitle">사용자·권한·기준정보를 관리하는 관리자 화면입니다.</p><div class="two-col"><div class="card"><div class="section-head"><h3>사용자 관리</h3><button class="primary" data-toast="사용자 추가 모달을 열었습니다.">사용자 추가</button></div><table class="table"><thead><tr><th>사번</th><th>이름</th><th>권한</th><th>상태</th></tr></thead><tbody>${[['admin','관리자','시스템 관리자','활성'],['10004','김덕우','품질 관리자','활성'],['10012','이현장','생산 담당','대기']].map(r=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td><td>${r[2]}</td><td><span class="status ${r[3]==='대기'?'warn':''}">${r[3]}</span></td></tr>`).join('')}</tbody></table></div><div class="card soft"><div class="section-head"><h3>프로토타입 상태</h3><span>DEMO</span></div><p style="font-size:12px;color:var(--muted);line-height:1.8">인증 · 더미 처리<br>데이터 조회 · 로컬 상수<br>API 연결 · 없음<br>DB 연결 · 없음</p><div style="height:8px;background:#e6e8ee;border-radius:99px;overflow:hidden"><div style="height:100%;width:100%;background:var(--green)"></div></div><p style="font-size:11px;color:var(--green);margin-bottom:0">프로토타입 준비 완료</p></div></div>`}
function render(){if(!state.loggedIn){login();return}const views={ai:home,dashboard,operation,reports,system};document.querySelector('#app').innerHTML=layout(views[state.page]());document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{state.page=b.dataset.page;render()}));$('#logout').addEventListener('click',()=>{state.loggedIn=false;login();});document.querySelectorAll('[data-toast]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.toast)));if(state.page==='ai'){$('#ask-form').addEventListener('submit',e=>{e.preventDefault();$('#response').classList.add('show');$('#response').scrollIntoView({behavior:'smooth',block:'nearest'});});}}
render();
