/**
 * API 엔드포인트 카탈로그 — 「API_목록_ver01.xlsx」 236건 + 백엔드 구현 확장분
 *
 * 명세서를 코드로 옮긴 단일 원본입니다. 서비스 함수 · 목(mock) 라우터 · 권한 판정이
 * 모두 이 표를 참조하므로, 명세가 바뀌면 이 파일만 고치면 됩니다.
 *
 *  key       서비스 함수명과 동일한 식별자
 *  domain    도메인 구분          screen    화면명
 *  name      API명                method/path  HTTP 메서드 · 경로
 *  params    요청 파라미터        response  응답 주요 필드
 *  roles     접근 권한(부서)      blind     데이터 권한(마스킹 대상 항목)
 *  tables    참조 테이블          priority  1=1차 필수 / 2=2차 / 3=선택
 *  live      true 면 목(mock) 모드에서도 실 서버로 호출합니다 (백엔드 구현 완료분)
 */
export const ENDPOINTS = {

  /* ═══ 인증·공통 ═══ */
  postAuthLogin: {
    no: 1, domain: '인증·공통', comp: 'CM-03', screen: '공통', funcId: 'CM-03-F02',
    name: '로그인', method: 'POST', path: '/api/v1/auth/login',
    params: 'loginId, password',
    response: 'accessToken, refreshToken, user(empNo,name,dept,pos)',
    roles: '비로그인', blind: [], live: true, priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_login_hist',
    note: '로그인 성공/실패 모두 접속 이력 기록',
  },
  postAuthLogout: {
    no: 2, domain: '인증·공통', comp: 'CM-03', screen: '공통', funcId: 'CM-03-F02',
    name: '로그아웃', method: 'POST', path: '/api/v1/auth/logout',
    params: '',
    response: 'success',
    roles: '전 부서', blind: [], live: true, priority: 1,
    tables: 'ax.tb_sys_login_hist',
  },
  postAuthRefresh: {
    no: 3, domain: '인증·공통', comp: 'CM-03', screen: '공통', funcId: 'CM-03-F02',
    name: '토큰 갱신', method: 'POST', path: '/api/v1/auth/refresh',
    params: 'refreshToken',
    response: 'accessToken',
    roles: '전 부서', blind: [], live: true, priority: 1,
    tables: '',
  },
  getAuthMe: {
    no: 4, domain: '인증·공통', comp: 'CM-01', screen: '공통', funcId: 'CM-01-F01',
    name: '내 정보·권한 조회', method: 'GET', path: '/api/v1/auth/me',
    params: '',
    response: 'user, dept, menuPerms[], dataPerms[], servingModelVer',
    roles: '전 부서', blind: [], live: true, priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_dept, ax.tb_sys_dept_menu_perm, ax.tb_sys_dept_data_perm',
    note: '메뉴/데이터 권한을 한 번에 반환 — 프론트 전 화면의 권한 판정 기준',
  },
  postAuthSwitch: {
    no: 5, domain: '인증·공통', comp: 'CM-02', screen: '공통', funcId: 'CM-02-F02',
    name: '계정 전환', method: 'POST', path: '/api/v1/auth/switch',
    params: 'empNo',
    response: 'accessToken, user',
    roles: '통합관리자', blind: [], live: true, priority: 3,
    tables: 'ax.tb_sys_user, ax.tb_log_audit',
    note: '프로토타입 데모 기능. 운영 전환 시 제외 또는 관리자 대행 로그인으로 한정',
  },
  postAuthPassword: {
    no: null, domain: '인증·공통', comp: 'CM-03', screen: '공통', funcId: 'CM-03-F08',
    name: '비밀번호 변경 (로그인 상태)', method: 'POST', path: '/api/v1/auth/password',
    params: 'currentPassword, newPassword, newPasswordConfirm',
    response: 'success, message',
    roles: '전 부서', blind: [], live: true, priority: 2,
    tables: 'ax.tb_sys_user, ax.tb_log_audit',
    note: '본인 비밀번호 변경. 비밀번호 찾기(/auth/password/reset)와 달리 현재 비밀번호를 확인한다',
  },
  getAuthSwitchTargets: {
    no: null, domain: '인증·공통', comp: 'CM-02', screen: '공통', funcId: 'CM-02-F01',
    name: '계정 전환 대상 목록', method: 'GET', path: '/api/v1/auth/switch-targets',
    params: '',
    response: 'items[{empNo,name,dept,pos}]',
    roles: '통합관리자', blind: [], live: true, priority: 3,
    tables: 'ax.tb_sys_user',
    note: '명세 외 — 백엔드 구현분(AUTH_API_FOR_WEB.md). 계정 전환 팝업 목록',
  },

  /* ─── 회원가입 · 비밀번호 찾기 (AUTH_API_FOR_WEB.md) ───
     명세서(ver01)에는 없고 백엔드에 먼저 구현된 API 입니다. 모두 비로그인 호출입니다. */
  getAuthSignupCheckEmpNo: {
    no: null, domain: '인증·공통', comp: 'CM-03', screen: '회원가입', funcId: 'CM-03-F03',
    name: '사번 중복 확인', method: 'GET', path: '/api/v1/auth/signup/check-emp-no',
    params: 'empNo',
    response: 'empNo, available, message',
    roles: '비로그인', blind: [], live: true, priority: 1,
    tables: 'ax.tb_sys_user',
    note: '형식(영문·숫자·하이픈·밑줄 4~30자)은 서버가 보지 않으므로 화면에서 먼저 거른다',
  },
  getAuthSignupDepts: {
    no: null, domain: '인증·공통', comp: 'CM-03', screen: '회원가입', funcId: 'CM-03-F03',
    name: '가입 가능 부서 목록', method: 'GET', path: '/api/v1/auth/signup/depts',
    params: '',
    response: 'depts[{deptId,deptNm,abbr,desc}]',
    roles: '비로그인', blind: [], live: true, priority: 1,
    tables: 'ax.tb_sys_dept',
    note: '통합관리자 부서는 목록에 없다 (스스로 신청 불가)',
  },
  postAuthEmailSendCode: {
    no: null, domain: '인증·공통', comp: 'CM-03', screen: '회원가입', funcId: 'CM-03-F04',
    name: '이메일 인증 코드 발송', method: 'POST', path: '/api/v1/auth/email/send-code',
    params: 'email, purpose(SIGNUP|PASSWORD_RESET)',
    response: 'email(마스킹), purpose, expiresAt, expireMinutes, resendAvailableInSec',
    roles: '비로그인', blind: [], live: true, priority: 1,
    tables: 'ax.tb_sys_email_verify',
    note: '재발송 대기 60초 · 일일 발송 상한 10회 (초과 시 E-RULE-001)',
  },
  postAuthEmailVerifyCode: {
    no: null, domain: '인증·공통', comp: 'CM-03', screen: '회원가입', funcId: 'CM-03-F04',
    name: '이메일 인증 코드 검증', method: 'POST', path: '/api/v1/auth/email/verify-code',
    params: 'email, purpose, code',
    response: 'verificationToken, purpose, expireMinutes',
    roles: '비로그인', blind: [], live: true, priority: 1,
    tables: 'ax.tb_sys_email_verify',
    note: '토큰은 10분 유효한 1회용 · 시도 5회 초과 시 코드 재요청',
  },
  postAuthSignup: {
    no: null, domain: '인증·공통', comp: 'CM-03', screen: '회원가입', funcId: 'CM-03-F05',
    name: '가입 신청', method: 'POST', path: '/api/v1/auth/signup',
    params: 'empNo, name, deptId, pos, email, verificationToken, password, passwordConfirm',
    response: 'empNo, email(마스킹), state(PENDING), message',
    roles: '비로그인', blind: [], live: true, priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_email_verify, ax.tb_log_audit',
    note: '가입 즉시 로그인 불가 — 전산팀 승인 후 사용 가능(PENDING)',
  },
  postAuthPasswordForgot: {
    no: null, domain: '인증·공통', comp: 'CM-03', screen: '비밀번호 찾기', funcId: 'CM-03-F06',
    name: '비밀번호 찾기 인증 코드 발송', method: 'POST', path: '/api/v1/auth/password/forgot',
    params: 'empNo, email',
    response: 'email(마스킹), expireMinutes, message',
    roles: '비로그인', blind: [], live: true, priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_email_verify',
    note: '계정 열거 방지 — 사번·이메일이 틀려도 동일한 성공 응답이 온다',
  },
  postAuthPasswordReset: {
    no: null, domain: '인증·공통', comp: 'CM-03', screen: '비밀번호 찾기', funcId: 'CM-03-F07',
    name: '비밀번호 재설정', method: 'POST', path: '/api/v1/auth/password/reset',
    params: 'verificationToken, newPassword, newPasswordConfirm',
    response: 'success, empNo, message',
    roles: '비로그인', blind: [], live: true, priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_email_verify, ax.tb_log_audit',
    note: '연속 실패로 잠긴 계정은 재설정 시 자동 해제된다',
  },

  getCommonDataRange: {
    no: null, domain: '인증·공통', comp: 'CM-01', screen: '공통', funcId: 'CM-01-F04',
    name: '실적 데이터 보유 기간 조회', method: 'GET', path: '/api/v1/common/data-range',
    params: 'plantCd, processId',
    response: 'plantCd, processId, fromDate, toDate',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'mes.*',
    note: '앱 부팅 시 1회. 날짜 선택기 기본값을 toDate 로 잡는다 — 오늘로 두면 실적이 없어 0 으로 보인다. processId 를 주면 그 공정의 구간',
  },
  getSystemUsersPending: {
    no: null, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F06',
    name: '승인 대기 계정 목록', method: 'GET', path: '/api/v1/system/users/pending',
    params: '',
    response: 'items[{empNo,name,dept,deptId,pos,email,requestedAt}]',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_sys_user',
    note: '회원가입(PENDING) 신청 목록. 명세 외 — 백엔드 구현분',
  },
  postSystemUsersByEmpNoApprove: {
    no: null, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F07',
    name: '회원가입 승인·반려', method: 'POST', path: '/api/v1/system/users/{empNo}/approve',
    params: 'approve, reason',
    response: 'empNo, state',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_sys_user, ax.tb_log_audit',
    note: '승인하면 PENDING → ACTIVE. 명세 외 — 백엔드 구현분',
  },
  postProductionResultsExport: {
    no: null, domain: '생산관리', comp: 'PR-02', screen: '생산 실적 조회', funcId: 'PR-02-F08',
    name: '실적 집계 내려받기', method: 'POST', path: '/api/v1/production/results/export',
    params: 'fromDate, toDate, procCd, itemCd, format',
    response: 'fileUrl 또는 바이너리',
    roles: '전 부서', blind: ['qty', 'yield'], priority: 2,
    tables: 'mes.*, ax.tb_log_download',
    note: '명세 외 — 백엔드 구현분. 내려받기 이력이 남는다',
  },

  getMenus: {
    no: 6, domain: '인증·공통', comp: 'CM-01', screen: '공통', funcId: 'CM-01-F01',
    name: '메뉴 트리 조회', method: 'GET', path: '/api/v1/menus',
    params: '',
    response: 'groups[{group,solo,items[{id,name,tag}]}]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_sys_menu, ax.tb_sys_menu_group, ax.tb_sys_dept_menu_perm',
    note: '접근 가능 항목만 반환',
  },
  getCommonCodes: {
    no: 7, domain: '인증·공통', comp: 'CM-05', screen: '공통', funcId: '',
    name: '공통코드 조회', method: 'GET', path: '/api/v1/common/codes',
    params: 'groupCd',
    response: 'codes[{cd,nm,sort,useYn}]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_sys_code, ax.tb_sys_code_group',
    note: '비가동 표준분류·불량유형·상태값 등',
  },
  getCommonMastersProcesses: {
    no: 8, domain: '인증·공통', comp: 'CM-05', screen: '공통', funcId: '',
    name: '공정 목록 조회', method: 'GET', path: '/api/v1/common/masters/processes',
    params: '',
    response: 'processes[{id,name,pre,eqptCnt,targetYield,capacity}]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'mes.tb_md_workcenter, ax.tb_sys_plant',
    note: 'Press/A Plating/B Plating/Coating',
  },
  getCommonMastersEquipments: {
    no: 9, domain: '인증·공통', comp: 'CM-05', screen: '공통', funcId: '',
    name: '설비 목록 조회', method: 'GET', path: '/api/v1/common/masters/equipments',
    params: 'processId, keyword',
    response: 'equipments[{eqptCd,eqptNm,wcCd,state}]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'mes.tb_md_eqpt, mes.tb_md_eqpt_by_workcenter',
  },
  getCommonMastersProducts: {
    no: 10, domain: '인증·공통', comp: 'DB-02', screen: '공통', funcId: 'DB-02-F01',
    name: '제품 목록 조회', method: 'GET', path: '/api/v1/common/masters/products',
    params: 'keyword, familyCd, customerCd, projectCd, sort(rank|name|family), page, size',
    response: 'products[{code,name,family,customer,project,rank,seq}], meta',
    roles: '전 부서', blind: ['customer'], priority: 1,
    tables: 'ax.tb_prod_product, ax.tb_prod_family, ax.tb_prod_customer, ax.tb_prod_project',
    note: '제품 선택 팝업(113종) 검색·필터·정렬 대응',
  },
  getCommonMastersCustomers: {
    no: 11, domain: '인증·공통', comp: 'CM-05', screen: '공통', funcId: '',
    name: '고객사 목록 조회', method: 'GET', path: '/api/v1/common/masters/customers',
    params: '',
    response: 'customers[{code,name}]',
    roles: '전 부서', blind: ['customer'], priority: 1,
    tables: 'ax.tb_prod_customer',
  },
  getCommonMastersDefectTypes: {
    no: 12, domain: '인증·공통', comp: 'CM-05', screen: '공통', funcId: '',
    name: '불량 유형 목록 조회', method: 'GET', path: '/api/v1/common/masters/defect-types',
    params: 'processId',
    response: 'defectTypes[{code,name,category}]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'mes.tb_md_defect, mes.tb_md_defect_by_item, ax.tb_ai_defect_tag',
  },
  getCommonMastersMolds: {
    no: 13, domain: '인증·공통', comp: 'CM-05', screen: '공통', funcId: '',
    name: '금형 목록 조회', method: 'GET', path: '/api/v1/common/masters/molds',
    params: 'eqptCd',
    response: 'molds[{moldCd,moldNm,shotCnt,remainShot}]',
    roles: '전 부서', blind: ['mold'], priority: 2,
    tables: 'mes.tb_md_mold, mes.tb_md_mold_by_eqpt',
  },

  /* ═══ AI 질의 ═══ */
  postAiChatAsk: {
    no: 14, domain: 'AI 질의', comp: 'AI-01', screen: '자연어 질의', funcId: 'AI-01-F01/F02',
    name: '자연어 질의 요청', method: 'POST', path: '/api/v1/ai/chat/ask',
    params: 'sessionId, question',
    response: 'messageId, intent(denied|unknown|trend|trace|downtime|metric), answerHtml, blocks[], agents[], sources[], followups[], elapsedMs',
    roles: '전 부서', blind: '*', priority: 1,
    tables: 'vec.tb_query_log, vec.tb_query_hit, vec.tb_doc_chunk, ax.tb_ai_chat_log, ax.tb_gls_term, ax.tb_ai_mask_rule',
    note: 'denied 분기 시 감사 로그 기록. unknown 분기는 답을 추정하지 않고 자료 소재 안내',
  },
  getAiChatSessionsBySessionId: {
    no: 15, domain: 'AI 질의', comp: 'AI-01', screen: '자연어 질의', funcId: 'AI-01-F07',
    name: '세션 대화 조회', method: 'GET', path: '/api/v1/ai/chat/sessions/{sessionId}',
    params: '',
    response: 'messages[{who,html,intent,ts}]',
    roles: '전 부서', blind: '*', priority: 1,
    tables: 'ax.tb_ai_chat_log',
  },
  deleteAiChatSessionsBySessionId: {
    no: 16, domain: 'AI 질의', comp: 'AI-01', screen: '자연어 질의', funcId: 'AI-01-F07',
    name: '새 대화 시작', method: 'DELETE', path: '/api/v1/ai/chat/sessions/{sessionId}',
    params: '',
    response: 'newSessionId',
    roles: '전 부서', blind: [], priority: 2,
    tables: 'ax.tb_ai_chat_log',
    note: '세션 맥락 초기화',
  },
  getAiChatSuggestions: {
    no: 17, domain: 'AI 질의', comp: 'AI-01', screen: '자연어 질의', funcId: 'AI-01-F04',
    name: '추천 질의 목록', method: 'GET', path: '/api/v1/ai/chat/suggestions',
    params: '',
    response: 'suggestions[{q,desc}]',
    roles: '전 부서', blind: [], priority: 2,
    tables: 'ax.tb_ai_chat_log',
    note: '현장 빈출 질의 기반 갱신',
  },
  postAiChatMessagesByMessageIdExport: {
    no: 18, domain: 'AI 질의', comp: 'AI-01', screen: '자연어 질의', funcId: 'AI-01-F05',
    name: '응답 결과 내려받기', method: 'POST', path: '/api/v1/ai/chat/messages/{messageId}/export',
    params: 'format(xls|csv)',
    response: 'file(binary)',
    roles: '전 부서', blind: '*', priority: 2,
    tables: 'ax.tb_rpt_download_log',
    note: 'blind 항목 제외 후 저장',
  },
  postAiChatMessagesByMessageIdFeedback: {
    no: 19, domain: 'AI 질의', comp: 'SY-08', screen: '자연어 질의', funcId: 'AI-01-F03',
    name: '응답 평가', method: 'POST', path: '/api/v1/ai/chat/messages/{messageId}/feedback',
    params: 'rating(good|bad), comment',
    response: 'success',
    roles: '전 부서', blind: [], priority: 2,
    tables: 'ax.tb_ai_chat_log',
    note: '파인튜닝 학습데이터 후보',
  },
  postAiChatAsr: {
    no: 20, domain: 'AI 질의', comp: 'AI-01', screen: '자연어 질의', funcId: 'AI-01-F06',
    name: '음성 입력 변환', method: 'POST', path: '/api/v1/ai/chat/asr',
    params: 'audio(multipart)',
    response: 'text',
    roles: '전 부서', blind: [], priority: 3,
    tables: '',
    note: '현장 PC·PDA 용. 프로토타입 미동작',
  },

  /* ═══ 대시보드 ═══ */
  getDashboardAiSummary: {
    no: 21, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '통합 요약 지표', method: 'GET', path: '/api/v1/dashboard/ai/summary',
    params: 'date',
    response: 'defectRate, uptimeRate, todayQty, pendingBorderline{cnt,maxWaitMin}',
    roles: '전 부서', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, ax.tb_met_metric_value',
    note: 'KPI 카드 4종',
  },
  getDashboardAiDefectTrend: {
    no: 22, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '시간대별 불량률 추이', method: 'GET', path: '/api/v1/dashboard/ai/defect-trend',
    params: 'date, interval(2h)',
    response: 'labels[], series[{name,data[]}], target',
    roles: '전 부서', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist',
    note: '전체 + 주 불량유형 2계열',
  },
  getDashboardAiLineProduction: {
    no: 23, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '라인별 생산량·불량률', method: 'GET', path: '/api/v1/dashboard/ai/line-production',
    params: 'date, processId',
    response: 'lines[{eqptCd,qty,defectRate}]',
    roles: '전 부서', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, mes.tb_md_eqpt',
  },
  getDashboardAiQualityIndex: {
    no: 24, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '공정 품질 지수(6축)', method: 'GET', path: '/api/v1/dashboard/ai/quality-index',
    params: 'date',
    response: 'axes[{label,value,target}]',
    roles: '전 부서', blind: ['yield'], priority: 1,
    tables: 'ax.tb_met_metric_value',
    note: '양품률·가동률·정시완료·검사정확도·이상대응·데이터정합',
  },
  getDashboardAiDefectComposition: {
    no: 25, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '불량 유형 구성', method: 'GET', path: '/api/v1/dashboard/ai/defect-composition',
    params: 'date, processId',
    response: 'segments[{label,value}], total, excludedBorderline',
    roles: '전 부서', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, mes.tb_md_defect',
    note: '경계 판정 건 제외 표기',
  },
  getDashboardAiProcessYield: {
    no: 26, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '공정별 수율', method: 'GET', path: '/api/v1/dashboard/ai/process-yield',
    params: 'date',
    response: 'items[{process,yield,level}], target, note',
    roles: '전 부서', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, mes.tb_md_workcenter',
  },
  getDashboardAiPlanVsActual: {
    no: 27, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '생산 계획 대비 실적', method: 'GET', path: '/api/v1/dashboard/ai/plan-vs-actual',
    params: 'date, interval(2h)',
    response: 'items[{slot,plan,actual}], cumPlan, cumActual, rate',
    roles: '전 부서', blind: ['qty', 'plan'], priority: 1,
    tables: 'mes.tb_pop_stock_hist',
  },
  getDashboardAiEquipmentUptimeHeatmap: {
    no: 28, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '설비별 시간대 가동률', method: 'GET', path: '/api/v1/dashboard/ai/equipment-uptime-heatmap',
    params: 'date, processId, interval(2h)',
    response: 'cols[], rows[], data[][], lo, hi',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'mes.tb_md_eqpt, ax.tb_met_metric_value',
    note: '낮을수록 진하게(invert)',
  },
  getDashboardAiLineProducts: {
    no: 29.1, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '설비 × 제품 실적', method: 'GET', path: '/api/v1/dashboard/ai/line-products',
    params: 'date, from, to, processId, page, size',
    response: 'lines[{eqptCd,eqptNm,processId,processNm,product,productNm,qty,okQty,ngQty,defectRate,plantNm,plantSource}]',
    roles: '전 부서', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_label_hist, mes.tb_md_eqpt',
    note: '실적 집계 조회 3단계(설비별) — 설비 × 공정 × 제품 한 줄. 실적 없는 설비는 빠집니다',
  },
  getDashboardAiLines: {
    no: 29, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '라인별 현황 목록', method: 'GET', path: '/api/v1/dashboard/ai/lines',
    params: 'date, processId',
    response: 'lines[{eqptCd,model,qty,defectRate,uptimeRate,state}]',
    roles: '전 부서', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_md_eqpt, mes.tb_pop_defect_hist',
    note: '행 클릭 → 설비 상세',
  },
  getProductionEquipmentsByEqptCd: {
    no: 30, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F03',
    name: '설비 상세 조회', method: 'GET', path: '/api/v1/production/equipments/{eqptCd}',
    params: 'date',
    response: 'eqptCd, model, qty, defectRate, uptimeRate, workcenter, iotState, stopElapsedMin',
    roles: '전 부서', blind: ['qty', 'yield', 'mold'], priority: 1,
    tables: 'mes.tb_md_eqpt, mes.tb_md_eqpt_by_workcenter',
    note: '모달',
  },
  getDashboardAiAlerts: {
    no: 31, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: '이상 알림 요약', method: 'GET', path: '/api/v1/dashboard/ai/alerts',
    params: 'hours(24)',
    response: 'alerts[{level,title,desc,elapsed,agent}]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_alm_alert',
  },
  getDashboardAiAgents: {
    no: 32, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: 'Agent 작동 현황 요약', method: 'GET', path: '/api/v1/dashboard/ai/agents',
    params: '',
    response: 'master{state,mode}, agents[{no,name,state,last,load}]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_ai_agent, ax.tb_ai_agent_run',
  },
  getDashboardAiBriefing: {
    no: 321, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: 'AI 일일 종합 브리핑', method: 'GET', path: '/api/v1/dashboard/ai/briefing',
    params: 'date, from, to',
    response: 'status, overallYield, overallDefectRate, todayQty, criticalLine, summaryLines, generatedAt',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'mes.tb_pop_label_hist, mes.tb_pop_defect_hist',
    timeoutMs: 300000, // sLLM 추론 — 로컬 실측 2문장에 약 24초
  },
  getDashboardAiCausePrescription: {
    no: 322, domain: '대시보드', comp: 'DB-01', screen: 'AI 통합 대시보드', funcId: 'DB-01-F01',
    name: 'AI 공정 원인 분석 및 처방 권고', method: 'GET', path: '/api/v1/dashboard/ai/cause-prescription',
    params: 'date, from, to, processId, eqptCd, threshold',
    response: 'selectedEqpt, availableEquipments, featureContributions, prescriptions, analyzedAt',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'mes.tb_pop_label_hist, mes.tb_pop_defect_hist',
    timeoutMs: 300000, // sLLM 추론 + FACA 문서 검색 — 브리핑보다 깁니다
  },
  getDashboardProcessSummary: {
    no: 33, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F10',
    name: '공정·제품 요약 지표', method: 'GET', path: '/api/v1/dashboard/process/summary',
    params: 'date, processId, productCodes[]',
    response: 'qty, okQty, ngQty, defectRate, yield, avgUptime, productCnt',
    roles: '전 부서', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, ax.tb_prod_product',
    note: '가중 평균 산출(총불량/총생산)',
  },
  getDashboardProcessDefectTrend: {
    no: 34, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F07',
    name: '시간대별 불량률 추이', method: 'GET', path: '/api/v1/dashboard/process/defect-trend',
    params: 'date, processId, productCodes[], interval',
    response: 'labels[], series[], target',
    roles: '전 부서', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist',
  },
  getDashboardProcessProductProduction: {
    no: 35, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F07',
    name: '제품별 생산량·불량률', method: 'GET', path: '/api/v1/dashboard/process/product-production',
    params: 'date, processId, productCodes[]',
    response: 'items[{product,qty,defectRate}]',
    roles: '전 부서', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, ax.tb_prod_item_map',
  },
  getDashboardProcessDefectComposition: {
    no: 36, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F07',
    name: '불량 유형 구성', method: 'GET', path: '/api/v1/dashboard/process/defect-composition',
    params: 'date, processId, productCodes[]',
    response: 'segments[{label,value}]',
    roles: '전 부서', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist',
  },
  getDashboardProcessProductYield: {
    no: 37, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F07',
    name: '제품별 수율', method: 'GET', path: '/api/v1/dashboard/process/product-yield',
    params: 'date, processId, productCodes[]',
    response: 'items[{product,yield,level}], target',
    roles: '전 부서', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist',
  },
  getDashboardProcessProductUptime: {
    no: 38, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F07',
    name: '제품별 가동률', method: 'GET', path: '/api/v1/dashboard/process/product-uptime',
    params: 'date, processId, productCodes[]',
    response: 'items[{product,uptimeRate}]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_met_metric_value',
    note: '설비 점유 기준',
  },
  getDashboardProcessProcessCompare: {
    no: 39, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F07',
    name: '공정 비교', method: 'GET', path: '/api/v1/dashboard/process/process-compare',
    params: 'date, productCodes[]',
    response: 'items[{process,defectRate}]',
    roles: '전 부서', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist',
    note: '동일 제품 구성 기준',
  },
  getDashboardProcessEquipmentUptimeHeatmap: {
    no: 40, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F07',
    name: '설비별 시간대 가동률', method: 'GET', path: '/api/v1/dashboard/process/equipment-uptime-heatmap',
    params: 'date, processId, interval',
    response: 'cols[], rows[], data[][]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'mes.tb_md_eqpt',
  },
  getDashboardProcessProducts: {
    no: 41, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F10',
    name: '제품별 상세 목록', method: 'GET', path: '/api/v1/dashboard/process/products',
    params: 'date, processId, productCodes[], sort',
    response: 'items[{product,family,customer,project,rank,qty,okQty,ngQty,defectRate,yield,uptimeRate}]',
    roles: '전 부서', blind: ['qty', 'yield', 'customer'], priority: 1,
    tables: 'ax.tb_prod_product, mes.tb_pop_defect_hist',
    note: '생산량 내림차순 기본',
  },
  getDashboardProcessTopProducts: {
    no: 42, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F08',
    name: 'Top N 제품 조회', method: 'GET', path: '/api/v1/dashboard/process/top-products',
    params: 'topN(5|10|20|50|all)',
    response: 'productCodes[]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_prod_product, ax.tb_prod_family',
    note: 'SY-07 제품군 순위를 따름',
  },
  getDashboardProcessSelectionSummary: {
    no: 43, domain: '대시보드', comp: 'DB-02', screen: '공정 및 제품 대시보드', funcId: 'DB-02-F07',
    name: '선택 요약', method: 'GET', path: '/api/v1/dashboard/process/selection-summary',
    params: 'processId, productCodes[]',
    response: 'process{name,capacity,targetYield}, productCnt, currentYield, gap',
    roles: '전 부서', blind: ['yield'], priority: 2,
    tables: 'mes.tb_md_workcenter, ax.tb_prod_product',
  },
  getDashboardKpiSummary: {
    no: 44, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F01',
    name: 'KPI 요약(3종)', method: 'GET', path: '/api/v1/dashboard/kpi/summary',
    params: 'yearMonth',
    response: 'kpis[{no,name,weight,value,target,rate,level}], totalRate',
    roles: '품질보증팀·생산관리팀·전산팀·경영진·통합관리자', blind: ['qty', 'yield'], priority: 1,
    tables: 'ax.tb_met_metric_std, ax.tb_met_metric_value',
    note: '가중치 0.4/0.3/0.3',
  },
  getDashboardKpiTrend: {
    no: 45, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F01',
    name: 'KPI 추이', method: 'GET', path: '/api/v1/dashboard/kpi/trend',
    params: 'from, to',
    response: 'labels[], series[{name,data[]}], baseline(100)',
    roles: '상동', blind: ['yield'], priority: 1,
    tables: 'ax.tb_met_metric_value',
    note: '구축 전=100 지수',
  },
  getDashboardKpiDefectDistribution: {
    no: 46, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F01',
    name: '불량 유형 분포', method: 'GET', path: '/api/v1/dashboard/kpi/defect-distribution',
    params: 'yearMonth',
    response: 'segments[{label,value}]',
    roles: '상동', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist',
  },
  getDashboardKpiDefectTypeTrend: {
    no: 47, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F01',
    name: '월별 불량 유형 추이', method: 'GET', path: '/api/v1/dashboard/kpi/defect-type-trend',
    params: 'from, to, topN(2)',
    response: 'labels[], series[]',
    roles: '상동', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist',
  },
  getDashboardKpiAiPerformance: {
    no: 48, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F01',
    name: 'AI 성능 6축', method: 'GET', path: '/api/v1/dashboard/kpi/ai-performance',
    params: 'yearMonth',
    response: 'axes[{label,value,target}]',
    roles: '상동', blind: [], priority: 1,
    tables: 'ax.tb_ai_serving_profile, ax.tb_ai_model_asset',
  },
  getDashboardKpiManhourSaving: {
    no: 49, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F01',
    name: '부서별 작업공수 절감', method: 'GET', path: '/api/v1/dashboard/kpi/manhour-saving',
    params: 'from, to',
    response: 'items[{dept,index}], baseline(100)',
    roles: '상동', blind: [], priority: 1,
    tables: 'ax.tb_met_metric_value',
  },
  getDashboardKpiAchievementTrend: {
    no: 50, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F01',
    name: '월별 목표 달성률', method: 'GET', path: '/api/v1/dashboard/kpi/achievement-trend',
    params: 'from, to',
    response: 'labels[], series[]',
    roles: '상동', blind: ['yield'], priority: 1,
    tables: 'ax.tb_met_metric_value',
    note: 'KPI 3종 가중 합산',
  },
  getDashboardKpiAiTargetStatus: {
    no: 51, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F01',
    name: 'AI 성능 목표 충족', method: 'GET', path: '/api/v1/dashboard/kpi/ai-target-status',
    params: 'yearMonth',
    response: 'segments[{label,value}], items[{item,target,actual,pass}]',
    roles: '상동', blind: [], priority: 1,
    tables: 'ax.tb_ai_serving_profile',
    note: '5개 항목',
  },
  getDashboardKpiMonthlyMatrix: {
    no: 52, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F01',
    name: '월별 지표 실측값', method: 'GET', path: '/api/v1/dashboard/kpi/monthly-matrix',
    params: 'year',
    response: 'cols[], rows[], data[][]',
    roles: '상동', blind: ['qty', 'yield'], priority: 1,
    tables: 'ax.tb_met_metric_value',
    note: '히트맵',
  },
  getDashboardKpiBasis: {
    no: 53, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F02',
    name: 'KPI 측정 기준 조회', method: 'GET', path: '/api/v1/dashboard/kpi/basis',
    params: '',
    response: 'kpis[{no,name,formula,source,cycle,exclusion}]',
    roles: '상동', blind: [], priority: 1,
    tables: 'ax.tb_met_metric_std, ax.tb_met_metric_source',
    note: '모달',
  },
  postDashboardKpiEvidenceExport: {
    no: 54, domain: '대시보드', comp: 'DB-03', screen: '성과지표 대시보드', funcId: 'DB-03-F03',
    name: 'KPI 증빙 내려받기', method: 'POST', path: '/api/v1/dashboard/kpi/evidence-export',
    params: 'yearMonth, format(xls)',
    response: 'file(binary)',
    roles: '상동', blind: ['qty', 'yield'], priority: 2,
    tables: 'ax.tb_met_metric_value, ax.tb_rpt_download_log',
    note: '산출 근거 원천 데이터',
  },

  /* ═══ 생산관리 ═══ */
  getProductionMonitorSummary: {
    no: 55, domain: '생산관리', comp: 'PR-01', screen: '생산 모니터링', funcId: 'PR-01-F01',
    name: '모니터링 요약', method: 'GET', path: '/api/v1/production/monitor/summary',
    params: 'processId',
    response: 'running, warning, stopped, hourlyThroughput, stoppedDetail',
    roles: '품질보증팀·생산관리팀·제조팀·통합관리자', blind: ['qty'], priority: 1,
    tables: 'mes.tb_md_eqpt, mes.tb_pop_defect_hist',
  },
  getProductionMonitorEquipments: {
    no: 56, domain: '생산관리', comp: 'PR-01', screen: '생산 모니터링', funcId: 'PR-01-F01/F03',
    name: '설비별 실시간 현황', method: 'GET', path: '/api/v1/production/monitor/equipments',
    params: 'processId, lineRange(설비코드 전방 일치), model, state, page, size',
    response: 'items[{eqptCd,model,qty,defectRate,uptimeRate,strokeSpeed,lastCollectedAt,state}], meta',
    roles: '상동', blind: ['qty', 'yield', 'mold'], priority: 1,
    tables: 'mes.tb_md_eqpt, mes.tb_pop_defect_hist, ax.tb_met_metric_std',
    note: '10초 폴링. 운영 시 SSE 검토',
  },
  getProductionResults: {
    no: 57, domain: '생산관리', comp: 'PR-02', screen: '실적 집계·조회', funcId: 'PR-02-F01',
    name: '실적 집계 조회', method: 'GET', path: '/api/v1/production/results',
    params: 'from, to, unit(day|week|month), itemCd, lineCd, page, size',
    response: 'items[{period,inputQty,okQty,ngQty,defectRate,uptimeRate,downtimeMin}], summary, meta',
    roles: '품질보증팀·생산관리팀·경영진·통합관리자', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, mes.tb_pop_stock_hist, mes.tb_md_item',
  },
  getProductionResultsTrend: {
    no: 58, domain: '생산관리', comp: 'PR-02', screen: '실적 집계·조회', funcId: 'PR-02-F02',
    name: '실적 추이 차트', method: 'GET', path: '/api/v1/production/results/trend',
    params: 'from, to, unit, itemCd',
    response: 'labels[], series[]',
    roles: '상동', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist',
  },
  getProductionDayTargets: {
    no: 59.7, domain: '생산관리', comp: 'PR-03', screen: '일목표 마스터', funcId: 'PR-03-F04',
    name: '일목표 조회', method: 'GET', path: '/api/v1/production/day-targets',
    params: 'product, processId, date, page, size',
    response: 'items[{targetId,product,processId,applyFrom,targetQty,remark}], meta',
    roles: '생산관리팀·통합관리자', blind: ['qty'], priority: 2,
    tables: 'ax.tb_prod_day_target', live: true,
    note: 'date 를 주면 그 날짜에 유효한 한 건씩 · 안 주면 전 이력 · size=0 은 전건',
  },
  postProductionDayTargets: {
    no: 59.8, domain: '생산관리', comp: 'PR-03', screen: '일목표 마스터', funcId: 'PR-03-F04',
    name: '일목표 등록', method: 'POST', path: '/api/v1/production/day-targets',
    params: 'product, processId, applyFrom, targetQty, remark',
    response: 'targetId',
    roles: '생산관리팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_prod_day_target', live: true,
    note: '적용일부터 다음 적용일 전까지 유효 (종료일 없음) · 제품·공정·적용일 중복은 400',
  },
  putProductionDayTargetsByTargetId: {
    no: 59.9, domain: '생산관리', comp: 'PR-03', screen: '일목표 마스터', funcId: 'PR-03-F04',
    name: '일목표 수정', method: 'PUT', path: '/api/v1/production/day-targets/{targetId}',
    params: 'applyFrom, targetQty, remark',
    response: 'targetId',
    roles: '생산관리팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_prod_day_target', live: true,
    note: '제품·공정은 바꿀 수 없습니다 (바꾸면 다른 제품 목표를 덮어쓰는 것이라 삭제 후 등록과 뜻이 다릅니다)',
  },
  deleteProductionDayTargetsByTargetId: {
    no: 59.95, domain: '생산관리', comp: 'PR-03', screen: '일목표 마스터', funcId: 'PR-03-F04',
    name: '일목표 삭제', method: 'DELETE', path: '/api/v1/production/day-targets/{targetId}',
    params: '—',
    response: 'success',
    roles: '생산관리팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_prod_day_target', live: true,
  },
  getProductionDailyReportsSheet: {
    no: 59.5, domain: '생산관리', comp: 'PR-03', screen: '일일 생산현황 보고', funcId: 'PR-03-F01',
    name: '조간회의 자료 본문', method: 'GET', path: '/api/v1/production/daily-reports/sheet',
    params: 'targetDate, processId',
    response: 'targetDate, periodFrom, periodTo, weekFrom, weekDays, reportId, processId, processCds[], rows[{product,productNm,processId,processNm,qty,okQty,ngQty,weekQty,eqptCnt,targetQty,weekTargetQty,decision,dri,due}]',
    roles: '생산관리팀·통합관리자', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, ax.tb_prod_item_map, mes.tb_md_eqpt',
    note: '전일 20:00~당일 08:00 · processId 없으면 프레스 작업장 전부 · targetQty 는 제품별 목표가 없어 항상 null',
    live: true,
  },
  postProductionDailyReportsRows: {
    no: 59.6, domain: '생산관리', comp: 'PR-03', screen: '일일 생산현황 보고', funcId: 'PR-03-F03',
    name: '조간회의 결과 저장', method: 'POST', path: '/api/v1/production/daily-reports/rows',
    params: 'targetDate, rows[{product, targetQty, decision, dri, due}]',
    response: 'targetDate, savedCnt',
    roles: '생산관리팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_prod_daily_decision',
    note: '키는 (대상일, 제품) · 보낸 제품만 갱신 · null 이면 그 칸을 비움 · 확정 상태 없음',
    live: true,
  },
  getProductionDowntimesSummary: {
    no: 68, domain: '생산관리', comp: 'PR-05', screen: '비가동 관리', funcId: 'PR-05-F06/F08',
    name: '비가동 요약', method: 'GET', path: '/api/v1/production/downtimes/summary',
    params: 'date',
    response: 'totalMin, registeredCnt, unregisteredCnt, byReason[]',
    roles: '생산관리팀·제조팀·통합관리자', blind: [], priority: 1,
    tables: 'mes.tb_md_eqpt, ax.tb_met_metric_value',
  },
  getProductionDowntimes: {
    no: 69, domain: '생산관리', comp: 'PR-05', screen: '비가동 관리', funcId: 'PR-05-F01',
    name: '비가동 이력 조회', method: 'GET', path: '/api/v1/production/downtimes',
    params: 'date, eqptCd, reasonCd, registered, page, size',
    response: 'items[{eqptCd,stopAt,resumeAt,elapsedMin,registered,reasonCd,reasonNm,remark}], meta',
    roles: '생산관리팀·제조팀·통합관리자', blind: [], priority: 1,
    tables: 'mes.tb_md_eqpt, ax.tb_sys_code',
    note: '미등록 구간 포함',
  },
  getProductionDowntimesReasonSuggestion: {
    no: 70, domain: '생산관리', comp: 'PR-05', screen: '비가동 관리', funcId: 'PR-05-F02',
    name: 'Agent 사유 후보 제안', method: 'GET', path: '/api/v1/production/downtimes/reason-suggestion',
    params: 'eqptCd, stopAt',
    response: 'candidates[{reasonCd,reasonNm,confidence,basis}]',
    roles: '생산관리팀·제조팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_agent_run, mes.tb_md_eqpt',
    note: '⑨ 이상 알림 Agent',
  },
  postProductionDowntimes: {
    no: 71, domain: '생산관리', comp: 'PR-05', screen: '비가동 관리', funcId: 'PR-05-F03',
    name: '비가동 사유 등록', method: 'POST', path: '/api/v1/production/downtimes',
    params: 'eqptCd, stopAt, resumeAt, reasonCd, remark',
    response: 'downtimeId',
    roles: '생산관리팀·제조팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_code, ax.tb_met_metric_value',
    note: '가동률(KPI③) 산출 근거',
  },
  putProductionDowntimesByDowntimeId: {
    no: 72, domain: '생산관리', comp: 'PR-05', screen: '비가동 관리', funcId: 'PR-05-F04',
    name: '비가동 사유 수정', method: 'PUT', path: '/api/v1/production/downtimes/{downtimeId}',
    params: 'reasonCd, remark, resumeAt',
    response: 'success',
    roles: '생산관리팀·제조팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_log_audit',
    note: '변경 이력 보존',
  },

  /* ═══ 품질관리 ═══ */
  getQualityDefectsSummary: {
    no: 73, domain: '품질관리', comp: 'QC-01', screen: '불량 현황 조회', funcId: 'QC-01-F01',
    name: '불량 현황 요약', method: 'GET', path: '/api/v1/quality/defects/summary',
    params: 'from, to, processId, defectTypeCd',
    response: 'totalCnt, defectRate, momChange',
    roles: '품질보증팀·생산관리팀·제조팀·경영진·통합관리자', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist',
  },
  getQualityDefectsByType: {
    no: 74, domain: '품질관리', comp: 'QC-01', screen: '불량 현황 조회', funcId: 'QC-01-F02',
    name: '불량 유형별 분포', method: 'GET', path: '/api/v1/quality/defects/by-type',
    params: 'from, to, processId',
    response: 'items[{defectType,cnt,ratio,momChange}]',
    roles: '상동', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, mes.tb_md_defect',
  },
  getQualityDefectsByLine: {
    no: 75, domain: '품질관리', comp: 'QC-01', screen: '불량 현황 조회', funcId: 'QC-01-F03',
    name: '라인별 불량률', method: 'GET', path: '/api/v1/quality/defects/by-line',
    params: 'from, to, processId, topN(5)',
    response: 'items[{eqptCd,model,ngQty,defectRate,mainType}]',
    roles: '상동', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, mes.tb_md_eqpt',
  },
  getQualityAoiPredictionSummary: {
    no: 76, domain: '품질관리', comp: 'QC-02', screen: 'AOI 판정 분석·예측', funcId: 'QC-02-F01',
    name: '예측 요약', method: 'GET', path: '/api/v1/quality/aoi/prediction/summary',
    params: 'target, horizon, trainPeriod',
    response: 'predictedDefectRate, thresholdReachCnt, riskLotCnt, modelConfidence',
    roles: '품질보증팀·생산관리팀·제조팀·통합관리자', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, ax.tb_ai_serving_profile',
  },
  getQualityAoiPredictionTrendBand: {
    no: 77, domain: '품질관리', comp: 'QC-02', screen: 'AOI 판정 분석·예측', funcId: 'QC-02-F01/F03',
    name: '불량률 추이·예측 밴드', method: 'GET', path: '/api/v1/quality/aoi/prediction/trend-band',
    params: 'target, horizon',
    response: 'labels[], actual[], estimated[], bandLow[], bandHigh[], threshold, splitIndex',
    roles: '상동', blind: ['yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, ax.tb_ai_model_config',
    note: 'actual/estimated 구분 플래그 필수',
  },
  getQualityAoiPredictionEquipmentRisk: {
    no: 78, domain: '품질관리', comp: 'QC-02', screen: 'AOI 판정 분석·예측', funcId: 'QC-02-F01/F04/F05',
    name: '설비별 위험 예측·권고', method: 'GET', path: '/api/v1/quality/aoi/prediction/equipment-risk',
    params: 'target, horizon',
    response: 'items[{eqptCd,aoiCd,currentRate,plus2h,plus8h,thresholdEta,mainFactor,recommendation,confidence}]',
    roles: '상동', blind: ['yield', 'mold'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, mes.tb_md_mold, ax.tb_ai_agent_run',
    note: '④ 원인 분석 Agent',
  },
  getQualityAoiPredictionLotRisk: {
    no: 79, domain: '품질관리', comp: 'QC-02', screen: 'AOI 판정 분석·예측', funcId: 'QC-02-F06',
    name: '출하 전 위험 LOT', method: 'GET', path: '/api/v1/quality/aoi/prediction/lot-risk',
    params: 'target',
    response: 'items[{lotNo,model,customer,shipDue,lrrProbability,basis,recommendation}]',
    roles: '상동', blind: ['customer', 'yield'], priority: 1,
    tables: 'mes.tb_pop_label_hist, mes.tb_pop_defect_hist',
    note: '과거 LRR 통보 이력 학습',
  },
  getQualityAoiPredictionRemainingEstimate: {
    no: 80, domain: '품질관리', comp: 'QC-02', screen: 'AOI 판정 분석·예측', funcId: 'QC-02-F01',
    name: '잔여 시간 추가 발생 추정', method: 'GET', path: '/api/v1/quality/aoi/prediction/remaining-estimate',
    params: 'target, horizon',
    response: 'estimatedNgQty, estimatedRate, confidence',
    roles: '상동', blind: ['qty', 'yield'], priority: 2,
    tables: 'mes.tb_pop_defect_hist',
  },
  getQualityAoiInspectorDrift: {
    no: 81, domain: '품질관리', comp: 'QC-02', screen: 'AOI 판정 분석·예측', funcId: 'QC-02-F07',
    name: 'AOI 판정 드리프트', method: 'GET', path: '/api/v1/quality/aoi/inspector-drift',
    params: 'from, to',
    response: 'items[{aoiCd,judgeCnt,drift,overRejectEst,underRejectEst,recheckMatchRate,borderlineRatio,state}]',
    roles: '상동', blind: [], priority: 1,
    tables: 'mes.tb_pop_defect_hist, ax.tb_ai_model_config',
    note: '드리프트 큰 검사기는 예측 신뢰도 하향',
  },
  getQualityAoiDefectTypeShift: {
    no: 82, domain: '품질관리', comp: 'QC-02', screen: 'AOI 판정 분석·예측', funcId: 'QC-02-F01',
    name: '불량 유형 구성 변화', method: 'GET', path: '/api/v1/quality/aoi/defect-type-shift',
    params: 'date, baseWeeks(4)',
    response: 'items[{defectType,today,baseAvg,change,interpretation}]',
    roles: '상동', blind: ['yield'], priority: 2,
    tables: 'mes.tb_pop_defect_hist',
  },
  postQualityAoiPredictionRecalculate: {
    no: 83, domain: '품질관리', comp: 'QC-02', screen: 'AOI 판정 분석·예측', funcId: 'QC-02-F02',
    name: '예측 재산출', method: 'POST', path: '/api/v1/quality/aoi/prediction/recalculate',
    params: 'target, horizon, trainPeriod',
    response: 'jobId, predictedAt',
    roles: '상동', blind: [], priority: 1,
    tables: 'ax.tb_ai_agent_run',
    note: '최근 2시간 판정 이력 반영',
  },
  getQualityAoiPredictionBasis: {
    no: 84, domain: '품질관리', comp: 'QC-02', screen: 'AOI 판정 분석·예측', funcId: 'QC-02-F08',
    name: '추정 근거·모델 조회', method: 'GET', path: '/api/v1/quality/aoi/prediction/basis',
    params: '',
    response: 'model, trainPeriod, features[], validation{}, limitations[]',
    roles: '상동', blind: [], priority: 2,
    tables: 'ax.tb_ai_model_config, ax.tb_ai_serving_profile',
    note: '모달',
  },

  /* ═══ 이상 알림 ═══ */
  getAlerts: {
    no: 102, domain: '이상 알림', comp: 'AL-01', screen: '알림 목록·상세', funcId: 'AL-01-F01',
    name: '알림 목록 조회', method: 'GET', path: '/api/v1/alerts',
    params: 'type(CRIT|WARN|LOW), eqptCd, period(today|7d|30d), ackState(OPEN|ACKED|CLOSED), page, size',
    response: 'items[{alertId,level,type,eqptCd,basisValue,threshold,agent,occurredAt,elapsed,ackState}], meta',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_alm_alert, ax.tb_alm_cond',
    note: '심각도 + 최신 순 정렬',
  },
  getAlertsByAlertId: {
    no: 103, domain: '이상 알림', comp: 'AL-01', screen: '알림 목록·상세', funcId: 'AL-01-F02',
    name: '알림 상세 조회', method: 'GET', path: '/api/v1/alerts/{alertId}',
    params: '',
    response: 'eqptCd, eqptNm, lotNo, basisValue, threshold, mainDefectType, causeCandidates[], recommendation, agent',
    roles: '전 부서', blind: ['yield', 'mold'], priority: 1,
    tables: 'ax.tb_alm_alert, ax.tb_ai_agent_run',
  },
  postAlertsByAlertIdAck: {
    no: 104, domain: '이상 알림', comp: 'AL-01', screen: '알림 목록·상세', funcId: 'AL-01-F03',
    name: '알림 확인 처리', method: 'POST', path: '/api/v1/alerts/{alertId}/ack',
    params: 'actionNote',
    response: 'ackAt, ackBy',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_alm_alert, ax.tb_log_audit',
  },
  getAlertsEscalationTargets: {
    no: 105, domain: '이상 알림', comp: 'AL-01', screen: '알림 목록·상세', funcId: 'AL-01-F04',
    name: '승격 대상 조회', method: 'GET', path: '/api/v1/alerts/escalation-targets',
    params: '',
    response: 'stages[{stage,waitMin,targets[]}]',
    roles: '전 부서', blind: [], priority: 2,
    tables: 'ax.tb_alm_escalation_rule, ax.tb_alm_cond_escalation',
  },
  getAlertsSendLogs: {
    no: 106, domain: '이상 알림', comp: 'AL-01', screen: '알림 목록·상세', funcId: 'AL-01-F01',
    name: '알림 발송 로그 조회', method: 'GET', path: '/api/v1/alerts/send-logs',
    params: 'from, to, condId, channel, page, size',
    response: 'items[{ts,condNm,channel,recipient,result,delaySec}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_alm_send_log',
  },

  /* ═══ 보고서 ═══ */
  getReportsPressMorning: {
    no: 107, domain: '보고서', comp: 'RP-01', screen: '아침회의 자료 (PRESS)', funcId: 'RP-01-F01~F04',
    name: 'PRESS 아침회의 자료 조회', method: 'GET', path: '/api/v1/reports/press-morning',
    params: 'baseDate, processScope, state',
    response: 'summary{dayTarget,dayActual,avgRate,issueCnt}, rows[{state,process,issue,dayTarget,dayActual,rate,weekTarget,weekActual,weekRate,impactEqptCnt,decision,dri,due}], total{}',
    roles: '생산관리팀·제조팀·통합관리자', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, mes.tb_pop_stock_hist, ax.tb_met_metric_std',
    note: '신호등 판정',
  },
  getReportsPressMorningDecisions: {
    no: 108, domain: '보고서', comp: 'RP-01', screen: '아침회의 자료 (PRESS)', funcId: 'RP-01-F05',
    name: '금일 결정 사항·DRI 조회', method: 'GET', path: '/api/v1/reports/press-morning/decisions',
    params: 'baseDate',
    response: 'items[{team,action,dri,due}]',
    roles: '생산관리팀·제조팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_rpt_report',
  },
  getReportsPlatingMorning: {
    no: 109, domain: '보고서', comp: 'RP-02', screen: '아침회의 자료 (Plating·Coating)', funcId: 'RP-02',
    name: 'Plating·Coating 아침회의 자료 조회', method: 'GET', path: '/api/v1/reports/plating-morning',
    params: 'baseDate, processScope(all|A Plating|B Plating|Coating), state',
    response: 'summary{}, rows[], total{}',
    roles: '생산관리팀·제조팀·통합관리자', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, mes.tb_pop_stock_hist',
    note: '11개 라인',
  },
  getReportsShipPlan: {
    no: 110, domain: '보고서', comp: 'RP-03', screen: '연간 출하계획', funcId: 'RP-03-F01~F04',
    name: '연간 출하계획 조회', method: 'GET', path: '/api/v1/reports/ship-plan',
    params: 'planYear, modelCd, customerCd, unit(qty|amount)',
    response: 'months[], rows[{model,customer,total,monthly[12]}], grandTotal, monthlyTotal[], peakMonth',
    roles: '생산관리팀·경영진·통합관리자', blind: ['plan', 'customer', 'price'], priority: 1,
    tables: 'ax.tb_prod_product, ax.tb_prod_customer',
    note: '회계연도 8월 시작 12개월',
  },
  getReportsYieldByModel: {
    no: 111, domain: '보고서', comp: 'RP-04', screen: '제품별 수율', funcId: 'RP-04-F01~F04',
    name: '제품별 수율 조회', method: 'GET', path: '/api/v1/reports/yield-by-model',
    params: 'yearMonth, modelCd, processId',
    response: 'summary{inputQty,okQty,yield,ngQty,defectRate,target}, rows[{no,date,model,inputQty,okQty,ngQty,defectRate,yield,loss{11종},mgmt{3종}}]',
    roles: '품질보증팀·경영진·통합관리자', blind: ['qty', 'yield'], priority: 1,
    tables: 'mes.tb_pop_defect_hist, mes.tb_md_defect_by_item, mes.tb_pop_stock_hist',
    note: 'Loss 11종 + 관리항목 3종 분해',
  },
  getReportsLrrByCustomer: {
    no: 112, domain: '보고서', comp: 'RP-05', screen: '고객사별 LRR', funcId: 'RP-05-F01~F04',
    name: '고객사별 LRR 조회', method: 'GET', path: '/api/v1/reports/lrr-by-customer',
    params: 'baseYear, customerCd, unit(month|quarter|year)',
    response: 'summary{shipQty,lrrCnt,lrrRate,yoyImprove}, byDefectType[], byCustomerMonth[], byCustomerQuarter[], trend[]',
    roles: '품질보증팀·경영진·통합관리자', blind: ['qty', 'yield', 'customer'], priority: 1,
    tables: 'mes.tb_pop_label_hist, mes.tb_pop_defect_hist, ax.tb_prod_customer',
    note: '고객사 통보 접수 이력 테이블 신규 필요',
  },
  getReportsScrapMesVouchers: {
    no: 115, domain: '보고서', comp: 'RP-07', screen: '폐기 보고서 작성 위저드', funcId: 'RP-07-F01',
    name: 'MES 폐기 전표 조회 (1단계)', method: 'GET', path: '/api/v1/reports/scrap/mes-vouchers',
    params: 'from, to, processId, modelCd, defectTypeCd, originType, page, size',
    response: 'items[{voucherId,occurDate,lotNo,model,process,defectType,qty,originType,docNo}], meta',
    roles: '상동', blind: ['qty'], priority: 1,
    tables: 'mes.tb_pop_stock_hist, mes.tb_pop_defect_hist',
  },

  /* ═══ 시스템관리 ═══ */
  getSystemAccountsSummary: {
    no: 127, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F09',
    name: '계정 관리 요약', method: 'GET', path: '/api/v1/system/accounts/summary',
    params: '',
    response: 'userCnt{active,suspended}, deptCnt, switchableCnt, currentUser{}',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_sys_user, ax.tb_sys_dept',
  },
  getSystemUsers: {
    no: 128, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F01',
    name: '계정 목록 조회', method: 'GET', path: '/api/v1/system/users',
    params: 'keyword, deptId, state, page, size',
    response: 'items[{empNo,name,dept,pos,state,lastLoginAt,demo}], meta',
    roles: '전산팀·통합관리자', blind: ['worker'], priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_login_hist',
  },
  postSystemUsers: {
    no: 129, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F01',
    name: '계정 등록', method: 'POST', path: '/api/v1/system/users',
    params: 'empNo, name, deptId, pos, state, switchable',
    response: 'empNo',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_perm_log',
    note: '검증: 필수값·아이디 중복. 부서 권한 자동 상속',
  },
  putSystemUsersByEmpNo: {
    no: 130, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F02',
    name: '계정 수정', method: 'PUT', path: '/api/v1/system/users/{empNo}',
    params: 'empNo, name, deptId, pos, state, switchable',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_perm_log',
  },
  deleteSystemUsersByEmpNo: {
    no: 131, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F03',
    name: '계정 삭제', method: 'DELETE', path: '/api/v1/system/users/{empNo}',
    params: '',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_perm_log',
    note: '제약: 로그인 계정 삭제 불가. 감사·다운로드 이력은 보존',
  },
  patchSystemUsersByEmpNoState: {
    no: 132, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F04',
    name: '계정 사용/정지', method: 'PATCH', path: '/api/v1/system/users/{empNo}/state',
    params: 'state(사용|정지)',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_perm_log',
    note: '제약: 로그인 계정 정지 불가',
  },
  putSystemUsersByEmpNoDept: {
    no: 133, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F05',
    name: '계정 부서 이동', method: 'PUT', path: '/api/v1/system/users/{empNo}/dept',
    params: 'deptId',
    response: 'success, appliedMenuCnt, appliedDataCnt',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_user, ax.tb_sys_perm_log, ax.tb_log_audit',
    note: '이동 즉시 새 부서 권한 적용',
  },
  getSystemDeptsPermCompare: {
    no: 134, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F05',
    name: '부서별 권한 비교', method: 'GET', path: '/api/v1/system/depts/perm-compare',
    params: '',
    response: 'items[{deptId,menuCnt,dataCnt}]',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_sys_dept_menu_perm, ax.tb_sys_dept_data_perm',
    note: '부서 이동 모달',
  },
  getSystemDepts: {
    no: 135, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F06',
    name: '부서 목록 조회', method: 'GET', path: '/api/v1/system/depts',
    params: '',
    response: 'items[{deptId,abbr,desc,userCnt,menuCnt,dataCnt}]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_dept',
  },
  postSystemDepts: {
    no: 136, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F06',
    name: '부서 등록', method: 'POST', path: '/api/v1/system/depts',
    params: 'deptId, abbr, desc, initPermFrom',
    response: 'deptId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_dept, ax.tb_sys_dept_menu_perm',
    note: '검증: 부서명·약칭 필수, 중복 불가. 초기 권한 복사 옵션',
  },
  putSystemDeptsByDeptId: {
    no: 137, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F07',
    name: '부서 수정', method: 'PUT', path: '/api/v1/system/depts/{deptId}',
    params: 'deptId, abbr, desc',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_dept, ax.tb_sys_user',
    note: '부서명 변경 시 권한·소속 계정 연쇄 갱신',
  },
  deleteSystemDeptsByDeptId: {
    no: 138, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F08',
    name: '부서 삭제', method: 'DELETE', path: '/api/v1/system/depts/{deptId}',
    params: '',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_dept',
    note: '제약: 통합관리자 불가, 소속 계정 있으면 불가',
  },
  getSystemPermLogs: {
    no: 139, domain: '시스템관리', comp: 'SY-01', screen: '계정 관리', funcId: 'SY-01-F09',
    name: '계정·권한 변경 이력', method: 'GET', path: '/api/v1/system/perm-logs',
    params: 'from, to, target, actType, page, size',
    response: 'items[{ts,target,actType,detail,by}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_perm_log',
  },
  getSystemMenuPerms: {
    no: 140, domain: '시스템관리', comp: 'SY-02', screen: '메뉴 접근 권한', funcId: 'SY-02-F01',
    name: '메뉴 권한 매트릭스 조회', method: 'GET', path: '/api/v1/system/menu-perms',
    params: '',
    response: 'screens[{id,name,group,sub}], depts[], matrix{deptId:[screenId]}',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_menu, ax.tb_sys_menu_group, ax.tb_sys_dept_menu_perm',
    note: '메뉴 + 하위 화면 + 보고서 모듈',
  },
  putSystemMenuPerms: {
    no: 141, domain: '시스템관리', comp: 'SY-02', screen: '메뉴 접근 권한', funcId: 'SY-02-F02',
    name: '메뉴 권한 단건 변경', method: 'PUT', path: '/api/v1/system/menu-perms',
    params: 'deptId, screenId, allowed',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_dept_menu_perm, ax.tb_sys_perm_log',
    note: '제약: 통합관리자 조정 불가',
  },
  putSystemMenuPermsGroup: {
    no: 142, domain: '시스템관리', comp: 'SY-02', screen: '메뉴 접근 권한', funcId: 'SY-02-F03',
    name: '메뉴 권한 그룹 일괄 변경', method: 'PUT', path: '/api/v1/system/menu-perms/group',
    params: 'deptId, groupNm, allowed',
    response: 'changedCnt',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_dept_menu_perm, ax.tb_sys_perm_log',
  },
  postSystemMenuPermsCopy: {
    no: 143, domain: '시스템관리', comp: 'SY-02', screen: '메뉴 접근 권한', funcId: 'SY-02-F04',
    name: '부서 메뉴 권한 복사', method: 'POST', path: '/api/v1/system/menu-perms/copy',
    params: 'fromDeptId, toDeptId',
    response: 'copiedCnt',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_dept_menu_perm, ax.tb_sys_perm_log',
    note: '대상 부서 기존 권한 덮어쓰기. 데이터 권한은 미복사',
  },
  getSystemMenuPermsDeptStatus: {
    no: 144, domain: '시스템관리', comp: 'SY-02', screen: '메뉴 접근 권한', funcId: 'SY-02-F06',
    name: '부서별 적용 현황', method: 'GET', path: '/api/v1/system/menu-perms/dept-status',
    params: '',
    response: 'items[{deptId,menuCnt,dataCnt,userCnt}]',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_sys_dept_menu_perm, ax.tb_sys_dept_data_perm',
  },
  getSystemDataFields: {
    no: 145, domain: '시스템관리', comp: 'SY-03', screen: '데이터 접근 권한', funcId: 'SY-03-F01',
    name: '데이터 항목 목록', method: 'GET', path: '/api/v1/system/data-fields',
    params: '',
    response: 'items[{key,name,desc,columns[]}]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_data_field, ax.tb_sys_data_field_column',
    note: '7종',
  },
  getSystemDataPerms: {
    no: 146, domain: '시스템관리', comp: 'SY-03', screen: '데이터 접근 권한', funcId: 'SY-03-F01',
    name: '데이터 권한 매트릭스 조회', method: 'GET', path: '/api/v1/system/data-perms',
    params: '',
    response: 'fields[], depts[], matrix{deptId:[fieldKey]}',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_dept_data_perm',
  },
  putSystemDataPerms: {
    no: 147, domain: '시스템관리', comp: 'SY-03', screen: '데이터 접근 권한', funcId: 'SY-03-F02/F06',
    name: '데이터 권한 변경', method: 'PUT', path: '/api/v1/system/data-perms',
    params: 'deptId, fieldKey, allowed',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sys_dept_data_perm, ax.tb_sys_perm_log, ax.tb_log_audit',
    note: '제약: 통합관리자 조정 불가',
  },
  getSystemDataPermsPreview: {
    no: 148, domain: '시스템관리', comp: 'SY-03', screen: '데이터 접근 권한', funcId: 'SY-03-F03',
    name: '적용 미리보기', method: 'GET', path: '/api/v1/system/data-perms/preview',
    params: 'empNo',
    response: 'items[{fieldKey,name,rendered,masked}]',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_sys_dept_data_perm',
  },
  getSystemDataPermsByUser: {
    no: 149, domain: '시스템관리', comp: 'SY-03', screen: '데이터 접근 권한', funcId: 'SY-03-F04',
    name: '계정별 적용 결과', method: 'GET', path: '/api/v1/system/data-perms/by-user',
    params: 'page, size',
    response: 'items[{empNo,name,dept,allowedFields[],maskedFields[]}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_sys_dept_data_perm',
  },
  getSystemDataPermsAudit: {
    no: 150, domain: '시스템관리', comp: 'SY-03', screen: '데이터 접근 권한', funcId: 'SY-03-F05',
    name: '데이터 접근 감사 조회', method: 'GET', path: '/api/v1/system/data-perms/audit',
    params: 'from, to, empNo, fieldKey, page, size',
    response: 'items[{ts,empNo,dept,fieldKey,screen,action}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_log_audit',
    note: 'blind 열람 시도 이력',
  },
  getAlertConditionsSummary: {
    no: 151, domain: '시스템관리', comp: 'SY-04', screen: '이상 알림 발송 조건 관리', funcId: 'SY-04-F07',
    name: '발송 조건 요약', method: 'GET', path: '/api/v1/alert-conditions/summary',
    params: '',
    response: 'activeCnt, totalCnt, todaySentCnt{byChannel}, dedupCnt, avgDelaySec',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_alm_cond, ax.tb_alm_send_log',
  },
  getAlertConditions: {
    no: 152, domain: '시스템관리', comp: 'SY-04', screen: '이상 알림 발송 조건 관리', funcId: 'SY-04-F01',
    name: '발송 조건 목록 조회', method: 'GET', path: '/api/v1/alert-conditions',
    params: 'severity, channel, state, page, size',
    response: 'items[{condId,on,name,metric,op,threshold,duration,target,severity,channels[],groups[],validWindow,dedupMin}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_cond, ax.tb_alm_cond_channel, ax.tb_alm_cond_group',
  },
  postAlertConditions: {
    no: 153, domain: '시스템관리', comp: 'SY-04', screen: '이상 알림 발송 조건 관리', funcId: 'SY-04-F01',
    name: '발송 조건 등록', method: 'POST', path: '/api/v1/alert-conditions',
    params: 'name, metricStdId, op, threshold, duration, target, severity, channels[], groupIds[], validWindow, dedupMin',
    response: 'condId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_cond, ax.tb_alm_cond_channel, ax.tb_alm_cond_group',
    note: '감지 지표는 SY-13 등록 지표 참조',
  },
  putAlertConditionsByCondId: {
    no: 154, domain: '시스템관리', comp: 'SY-04', screen: '이상 알림 발송 조건 관리', funcId: 'SY-04-F02',
    name: '발송 조건 수정', method: 'PUT', path: '/api/v1/alert-conditions/{condId}',
    params: '동일',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_cond',
  },
  deleteAlertConditionsByCondId: {
    no: 152.5, domain: '시스템관리', comp: 'SY-04', screen: '이상 알림 발송 조건 관리', funcId: 'SY-04-F01',
    name: '발송 조건 삭제', method: 'DELETE', path: '/api/v1/alert-conditions/{condId}',
    params: '',
    response: 'success',
    roles: '통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_alm_cond, ax.tb_alm_cond_channel, ax.tb_alm_cond_group',
    note: '이미 알림이 발생한 조건은 409 — 중지로 안내',
  },
  patchAlertConditionsByCondIdState: {
    no: 155, domain: '시스템관리', comp: 'SY-04', screen: '이상 알림 발송 조건 관리', funcId: 'SY-04-F03',
    name: '발송 조건 활성/중지', method: 'PATCH', path: '/api/v1/alert-conditions/{condId}/state',
    params: 'on(true|false)',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_cond, ax.tb_log_audit',
    note: '즉시 반영',
  },
  postAlertConditionsByCondIdTestSend: {
    no: 156, domain: '시스템관리', comp: 'SY-04', screen: '이상 알림 발송 조건 관리', funcId: 'SY-04-F04',
    name: '발송 조건 테스트', method: 'POST', path: '/api/v1/alert-conditions/{condId}/test-send',
    params: '',
    response: 'sentCnt, recipients[]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_send_log',
    note: '테스트 플래그로 로그 기록',
  },
  getAlertRecipientsSummary: {
    no: 157, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F01',
    name: '수신자 관리 요약', method: 'GET', path: '/api/v1/alert-recipients/summary',
    params: '',
    response: 'groupCnt, recipientCnt{receiving,absent}, nightCnt, activeDutyCnt',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_alm_recip_group, ax.tb_alm_recipient, ax.tb_alm_duty',
  },
  getAlertRecipientGroups: {
    no: 158, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F01',
    name: '수신 그룹 목록', method: 'GET', path: '/api/v1/alert-recipient-groups',
    params: '',
    response: 'items[{groupId,name,channels[],validWindow,night,members[]}]',
    roles: '전산팀·통합관리자', blind: ['worker'], priority: 1,
    tables: 'ax.tb_alm_recip_group, ax.tb_alm_recip_group_channel, ax.tb_alm_recip_group_member',
  },
  postAlertRecipientGroups: {
    no: 159, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F01',
    name: '수신 그룹 등록', method: 'POST', path: '/api/v1/alert-recipient-groups',
    params: 'name, channels[], validWindow, night, memberEmpNos[]',
    response: 'groupId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_recip_group',
  },
  putAlertRecipientGroupsByGroupId: {
    no: 160, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F01',
    name: '수신 그룹 수정', method: 'PUT', path: '/api/v1/alert-recipient-groups/{groupId}',
    params: '동일',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_recip_group',
  },
  postAlertRecipientGroupsByGroupIdTestSend: {
    no: 161, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F02',
    name: '수신 그룹 테스트 발송', method: 'POST', path: '/api/v1/alert-recipient-groups/{groupId}/test-send',
    params: '',
    response: 'sentCnt',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_alm_send_log',
  },
  getAlertRecipients: {
    no: 162, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F03',
    name: '수신자 목록', method: 'GET', path: '/api/v1/alert-recipients',
    params: 'state, page, size',
    response: 'items[{empNo,name,dept,pos,mail,hp,messenger,night,state}], meta',
    roles: '전산팀·통합관리자', blind: ['worker'], priority: 1,
    tables: 'ax.tb_alm_recipient',
  },
  postAlertRecipients: {
    no: 163, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F03',
    name: '수신자 등록', method: 'POST', path: '/api/v1/alert-recipients',
    params: 'empNo, mail, hp, messenger, night',
    response: 'recipientId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_recipient',
  },
  putAlertRecipientsByRecipientId: {
    no: 164, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F03',
    name: '수신자 수정', method: 'PUT', path: '/api/v1/alert-recipients/{recipientId}',
    params: 'mail, hp, messenger, night',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_recipient',
  },
  patchAlertRecipientsByRecipientIdState: {
    no: 165, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F04',
    name: '수신/부재 토글', method: 'PATCH', path: '/api/v1/alert-recipients/{recipientId}/state',
    params: 'state(수신|부재)',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_recipient',
    note: '부재 시 대리 수신자로 대체',
  },
  getAlertDuties: {
    no: 166, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F05',
    name: '당번·대리 목록', method: 'GET', path: '/api/v1/alert-duties',
    params: 'from, to, groupId',
    response: 'items[{dutyId,from,to,group,main,sub,reason}]',
    roles: '전산팀·통합관리자', blind: ['worker'], priority: 1,
    tables: 'ax.tb_alm_duty',
  },
  postAlertDuties: {
    no: 167, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F05',
    name: '당번 등록', method: 'POST', path: '/api/v1/alert-duties',
    params: 'from, to, groupId, mainEmpNo, subEmpNo, reason',
    response: 'dutyId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_alm_duty',
  },
  putAlertDutiesByDutyId: {
    no: 168, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F05',
    name: '당번 수정', method: 'PUT', path: '/api/v1/alert-duties/{dutyId}',
    params: '동일',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_alm_duty',
  },
  deleteAlertDutiesByDutyId: {
    no: 168, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F05',
    name: '당번 삭제', method: 'DELETE', path: '/api/v1/alert-duties/{dutyId}',
    params: '동일',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_alm_duty',
  },
  getAlertEscalationRules: {
    no: 169, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F07',
    name: '승격 규칙 조회', method: 'GET', path: '/api/v1/alert-escalation-rules',
    params: 'stages[{stage,waitMin,targetGroupId}]',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_alm_escalation_rule',
  },
  putAlertEscalationRules: {
    no: 169, domain: '시스템관리', comp: 'SY-05', screen: '알림 수신자 관리', funcId: 'SY-05-F07',
    name: '승격 규칙 수정', method: 'PUT', path: '/api/v1/alert-escalation-rules',
    params: 'stages[{stage,waitMin,targetGroupId}]',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_alm_escalation_rule',
  },
  getGlossarySummary: {
    no: 170, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F06',
    name: '용어 사전 요약', method: 'GET', path: '/api/v1/glossary/summary',
    params: '',
    response: 'termCnt, variantCnt, domainCnt, myVariantCnt, noVariantTermCnt, byDomain[]',
    roles: '전 부서', blind: [], priority: 2,
    tables: 'ax.tb_gls_term, ax.tb_gls_variant, ax.tb_gls_domain',
  },
  getGlossaryTerms: {
    no: 171, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F05',
    name: '용어 목록 조회', method: 'GET', path: '/api/v1/glossary/terms',
    params: 'keyword, domainCd, page, size',
    response: 'items[{termId,term,definition,domain,variants[{variantId,word,byEmpNo,byName,at,editable}]}], meta',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_gls_term, ax.tb_gls_variant',
    note: 'editable = 등록 본인 여부',
  },
  getGlossaryDomains: {
    no: 171.5, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F01',
    name: '용어 분류 목록', method: 'GET', path: '/api/v1/glossary/domains',
    params: '',
    response: 'domains[{domainId,code,name}]',
    roles: '통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_gls_domain',
    note: 'code 를 용어 등록의 domainCd 에 넣습니다',
  },
  postGlossaryTerms: {
    no: 172, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F01',
    name: '공식 용어 등록', method: 'POST', path: '/api/v1/glossary/terms',
    params: 'term, definition, domainCd',
    response: 'termId',
    roles: '통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_gls_term',
    note: '관리자 전용',
  },
  putGlossaryTermsByTermId: {
    no: 173, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F01',
    name: '공식 용어 수정', method: 'PUT', path: '/api/v1/glossary/terms/{termId}',
    params: 'term, definition, domainCd',
    response: 'success',
    roles: '통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_gls_term',
    note: '관리자 전용',
  },
  postGlossaryTermsByTermIdVariants: {
    no: 174, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F02',
    name: '유사어 등록', method: 'POST', path: '/api/v1/glossary/terms/{termId}/variants',
    params: 'word',
    response: 'variantId',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_gls_variant',
    note: '등록자·등록일 자동 기록',
  },
  putGlossaryVariantsByVariantId: {
    no: 175, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F03',
    name: '유사어 수정', method: 'PUT', path: '/api/v1/glossary/variants/{variantId}',
    params: 'word',
    response: 'success',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_gls_variant',
    note: '등록 본인만 가능',
  },
  deleteGlossaryVariantsByVariantId: {
    no: 176, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F03',
    name: '유사어 삭제', method: 'DELETE', path: '/api/v1/glossary/variants/{variantId}',
    params: '',
    response: 'success',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_gls_variant',
    note: '등록 본인만 가능',
  },
  deleteGlossaryTermsByTermId: {
    no: 176.5, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F01',
    name: '공식 용어 삭제', method: 'DELETE', path: '/api/v1/glossary/terms/{termId}',
    params: '',
    response: 'success',
    roles: '통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_gls_term, ax.tb_gls_variant',
    note: '등록 본인만 가능 · 유사어도 함께 지워집니다',
  },
  postGlossaryNormalize: {
    no: 177, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F04',
    name: '용어 정규화 미리보기', method: 'POST', path: '/api/v1/glossary/normalize',
    params: 'text',
    response: 'normalizedText, replacements[{from,to,termId}]',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_gls_term, ax.tb_gls_variant',
  },
  postGlossaryReindex: {
    no: 178, domain: '시스템관리', comp: 'SY-06', screen: '용어 사전 관리', funcId: 'SY-06-F07',
    name: '용어 임베딩 재생성', method: 'POST', path: '/api/v1/glossary/reindex',
    params: '',
    response: 'jobId',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'vec.tb_term_embedding, vec.tb_ingest_job',
    note: 'SY-11 재색인과 연동',
  },
  getProductsFamilies: {
    no: 179, domain: '시스템관리', comp: 'SY-07', screen: '제품군 순위 관리', funcId: 'SY-07-F01',
    name: '제품군 순위 조회', method: 'GET', path: '/api/v1/products/families',
    params: '',
    response: 'items[{familyCd,familyNm,rank,productCnt,repProduct}]',
    roles: '전산팀·경영진·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_prod_family, ax.tb_prod_product',
  },
  putProductsFamiliesOrder: {
    no: 180, domain: '시스템관리', comp: 'SY-07', screen: '제품군 순위 관리', funcId: 'SY-07-F01/F02',
    name: '제품군 순위 변경', method: 'PUT', path: '/api/v1/products/families/order',
    params: 'orders[{familyCd,rank}]',
    response: 'success, recalculatedCnt',
    roles: '상동', blind: [], priority: 1,
    tables: 'ax.tb_prod_family, ax.tb_prod_rank_log',
    note: '제품군 순위 × 제품군 내 순서로 전체 rank 재계산',
  },
  getProductsFamiliesByFamilyCdProducts: {
    no: 181, domain: '시스템관리', comp: 'SY-07', screen: '제품군 순위 관리', funcId: 'SY-07-F03',
    name: '제품군 내 제품 순서 조회', method: 'GET', path: '/api/v1/products/families/{familyCd}/products',
    params: '',
    response: 'items[{code,name,customer,project,seq}]',
    roles: '상동', blind: ['customer'], priority: 1,
    tables: 'ax.tb_prod_product',
  },
  putProductsFamiliesByFamilyCdProductsOrder: {
    no: 182, domain: '시스템관리', comp: 'SY-07', screen: '제품군 순위 관리', funcId: 'SY-07-F03',
    name: '제품군 내 제품 순서 변경', method: 'PUT', path: '/api/v1/products/families/{familyCd}/products/order',
    params: 'orders[{code,seq}]',
    response: 'success',
    roles: '상동', blind: [], priority: 1,
    tables: 'ax.tb_prod_product, ax.tb_prod_rank_log',
  },
  postProductsFamiliesOrderReset: {
    no: 183, domain: '시스템관리', comp: 'SY-07', screen: '제품군 순위 관리', funcId: 'SY-07-F05',
    name: '기본 순서 복원', method: 'POST', path: '/api/v1/products/families/order/reset',
    params: '',
    response: 'success',
    roles: '상동', blind: [], priority: 2,
    tables: 'ax.tb_prod_family, ax.tb_prod_rank_log',
  },
  getProductsRanking: {
    no: 184, domain: '시스템관리', comp: 'SY-07', screen: '제품군 순위 관리', funcId: 'SY-07-F07',
    name: '현재 순위 상위 N 조회', method: 'GET', path: '/api/v1/products/ranking',
    params: 'topN(20)',
    response: 'items[{rank,code,family,customer,segment}]',
    roles: '상동', blind: ['customer'], priority: 1,
    tables: 'ax.tb_prod_product',
    note: '대시보드 Top N 기준',
  },
  getProductsRankLogs: {
    no: 185, domain: '시스템관리', comp: 'SY-07', screen: '제품군 순위 관리', funcId: 'SY-07-F06',
    name: '순위 변경 이력', method: 'GET', path: '/api/v1/products/rank-logs',
    params: 'page, size',
    response: 'items[{ts,type,detail,by}], meta',
    roles: '상동', blind: [], priority: 2,
    tables: 'ax.tb_prod_rank_log',
  },
  getAiChatHistorySummary: {
    no: 186, domain: '시스템관리', comp: 'SY-08', screen: '자연어 질의 이력', funcId: 'SY-08-F02',
    name: '질의 이력 요약', method: 'GET', path: '/api/v1/ai/chat/history/summary',
    params: 'from, to, userGroup',
    response: 'questionCnt, intentAccuracy, avgResponseSec, requeryRate, targetAccuracy',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_ai_chat_log, vec.tb_query_log',
  },
  getAiChatHistory: {
    no: 187, domain: '시스템관리', comp: 'SY-08', screen: '자연어 질의 이력', funcId: 'SY-08-F01',
    name: '질의 이력 조회', method: 'GET', path: '/api/v1/ai/chat/history',
    params: 'from, to, userGroup, intent, page, size',
    response: 'items[{ts,empNo,question,intent,agents[],responseSec,rating}], meta',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_ai_chat_log, ax.tb_ai_chat_agent',
  },
  getAiChatHistoryByMessageId: {
    no: 188, domain: '시스템관리', comp: 'SY-08', screen: '자연어 질의 이력', funcId: 'SY-08-F04',
    name: '질의 상세 조회', method: 'GET', path: '/api/v1/ai/chat/history/{messageId}',
    params: '',
    response: 'question, intent, prompt, answer, hits[{docId,chunkId,score}], agents[], elapsedMs',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'vec.tb_query_log, vec.tb_query_hit, vec.tb_doc_chunk',
  },
  postAiChatHistoryExportTrainset: {
    no: 189, domain: '시스템관리', comp: 'SY-08', screen: '자연어 질의 이력', funcId: 'SY-08-F05',
    name: '학습데이터 내보내기', method: 'POST', path: '/api/v1/ai/chat/history/export-trainset',
    params: 'from, to, ratingFilter, format(jsonl)',
    response: 'file(binary), sampleCnt',
    roles: '전산팀·통합관리자', blind: [], priority: 3,
    tables: 'ax.tb_ai_chat_log',
    note: '파인튜닝 학습데이터',
  },
  getAuditLogs: {
    no: 190, domain: '시스템관리', comp: 'SY-09', screen: '보안 감사 로그', funcId: 'SY-09-F01',
    name: '감사 로그 조회', method: 'GET', path: '/api/v1/audit-logs',
    params: 'from, to, type, userGroup, empNo, page, size',
    response: 'items[{ts,type,empNo,dept,target,detail,ip}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_log_audit, ax.tb_sys_login_hist, ax.tb_sys_perm_log',
    note: 'append-only. 수정·삭제 API 미제공',
  },
  getAiModelConfig: {
    no: 191, domain: '시스템관리', comp: 'SY-10', screen: 'AI 모델 설정', funcId: 'SY-10-F01/F02',
    name: 'AI 모델 설정 조회', method: 'GET', path: '/api/v1/ai/model-config',
    params: '',
    response: 'thresholds[{agentCd,metric,value}], classification{judgeBoundary,borderlineRange,hitlCriteria}',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_model_config, ax.tb_ai_agent',
  },
  putAiModelConfig: {
    no: 192, domain: '시스템관리', comp: 'SY-10', screen: 'AI 모델 설정', funcId: 'SY-10-F01/F02/F04',
    name: 'AI 모델 설정 저장', method: 'PUT', path: '/api/v1/ai/model-config',
    params: 'thresholds[], classification{}',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_model_config, ax.tb_log_audit',
    note: '즉시 Agent 반영',
  },
  getAiMaskRules: {
    no: 193, domain: '시스템관리', comp: 'SY-10', screen: 'AI 모델 설정', funcId: 'SY-10-F03',
    name: '보안 필터링 패턴 목록', method: 'GET', path: '/api/v1/ai/mask-rules',
    params: '',
    response: 'items[{ruleId,name,targetFields[],action,customerPolicy,useYn}]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_mask_rule, ax.tb_ai_mask_rule_column',
    note: '⑦ 보안 필터링 Agent',
  },
  postAiMaskRules: {
    no: 194, domain: '시스템관리', comp: 'SY-10', screen: 'AI 모델 설정', funcId: 'SY-10-F03',
    name: '보안 필터링 패턴 등록', method: 'POST', path: '/api/v1/ai/mask-rules',
    params: 'name, targetFields[], action, customerPolicy, useYn',
    response: 'ruleId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_mask_rule, ax.tb_ai_mask_rule_column',
  },
  postAiMaskRulesByRuleId: {
    no: 194, domain: '시스템관리', comp: 'SY-10', screen: 'AI 모델 설정', funcId: 'SY-10-F03',
    name: '보안 필터링 패턴 등록 (ID 지정)', method: 'POST', path: '/api/v1/ai/mask-rules/{ruleId}',
    params: 'name, fieldKey, targetFields, action, customerId, customerPolicy',
    response: 'ruleId',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_ai_mask_rule, ax.tb_log_audit',
    note: '서버가 PUT 과 함께 열어 둔 별칭. 웹은 신규는 컬렉션 POST, 수정은 PUT 을 씁니다',
  },
  putAiMaskRulesByRuleId: {
    no: 194, domain: '시스템관리', comp: 'SY-10', screen: 'AI 모델 설정', funcId: 'SY-10-F03',
    name: '보안 필터링 패턴 수정', method: 'PUT', path: '/api/v1/ai/mask-rules/{ruleId}',
    params: 'name, targetFields[], action, customerPolicy, useYn',
    response: 'ruleId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_mask_rule, ax.tb_ai_mask_rule_column',
  },
  getAiModelReleasesSummary: {
    no: 195, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F01',
    name: '모델 버전 요약', method: 'GET', path: '/api/v1/ai/model-releases/summary',
    params: '',
    response: 'serving{ver,mode,appliedAt}, releaseCnt, vecCompletedCnt, ftCompletedCnt',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_ai_serving_profile, ax.tb_ai_model_asset',
  },
  getAiModelReleases: {
    no: 196, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F01',
    name: '릴리스 목록 조회', method: 'GET', path: '/api/v1/ai/model-releases',
    params: 'state, page, size',
    response: 'items[{ver,vecId,ftId,registeredAt,registeredBy,state,mode,note}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_serving_asset, ax.tb_ai_serving_profile',
  },
  postAiModelReleases: {
    no: 197, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F01',
    name: '릴리스 등록', method: 'POST', path: '/api/v1/ai/model-releases',
    params: 'ver, vecId, ftId, mode, note',
    response: 'ver',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_serving_asset',
    note: '완료 상태 빌드만 선택 가능',
  },
  getAiModelReleasesByVerApplyPreview: {
    no: 198, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F02',
    name: '적용 전 성능 비교', method: 'GET', path: '/api/v1/ai/model-releases/{ver}/apply-preview',
    params: '',
    response: 'current{intent,cite,refuse,halluc}, target{...}, delta{...}',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_model_asset, ax.tb_ai_serving_profile',
    note: '환각률은 낮을수록 개선',
  },
  postAiModelReleasesByVerApply: {
    no: 199, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F03',
    name: '서비스 적용', method: 'POST', path: '/api/v1/ai/model-releases/{ver}/apply',
    params: 'mode(즉시 전환|점진 전환)',
    response: 'servingVer, appliedAt',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_serving_profile, ax.tb_ai_serving_route, ax.tb_ai_serving_deploy_log',
    note: '제약: 동시에 하나만 서비스 중',
  },
  postAiModelReleasesRollback: {
    no: 200, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F04',
    name: '직전 버전 롤백', method: 'POST', path: '/api/v1/ai/model-releases/rollback',
    params: '',
    response: 'servingVer',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_serving_profile, ax.tb_ai_serving_deploy_log',
  },
  postAiModelReleasesByVerArchive: {
    no: 201, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F05',
    name: '릴리스 보관', method: 'POST', path: '/api/v1/ai/model-releases/{ver}/archive',
    params: '',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_ai_serving_asset',
    note: '제약: 서비스 중 버전 보관 불가',
  },
  getAiVectorBuilds: {
    no: 202, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F06',
    name: '벡터 인덱스 목록', method: 'GET', path: '/api/v1/ai/vector-builds',
    params: 'state, page, size',
    response: 'items[{vecId,startedAt,duration,state,sources[],docCnt,chunkCnt,embedModel,dim,size}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'vec.tb_ingest_job, vec.tb_embed_model, vec.tb_doc',
  },
  getAiEmbedModels: {
    no: 200.5, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F02',
    name: '임베딩 모델 목록', method: 'GET', path: '/api/v1/ai/embed-models',
    params: '',
    response: 'items[{embedModelId,key,name,provider,providerNm,dim,maxTokens,onPrem,current,remark}]',
    roles: '통합관리자', blind: [], priority: 2,
    tables: 'vec.tb_embed_model',
    note: 'onPrem=false 는 외부 API — 기밀 문서 전송 금지',
  },
  getAiAssets: {
    no: 200.6, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F02',
    name: '모델 자산 목록', method: 'GET', path: '/api/v1/ai/assets',
    params: 'kind(LLM_BASE|LORA|EMBED|RERANK)',
    response: 'items[{assetId,kind,kindNm,assetKey,version,name,baseModel,dim,maxTokens,state,stateNm,onPrem,verifiedAt}]',
    roles: '통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_ai_model_asset',
    note: '파인튜닝 실행 때마다 한 건씩 쌓입니다',
  },
  postAiVectorBuilds: {
    no: 203, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F06',
    name: '재색인 실행', method: 'POST', path: '/api/v1/ai/vector-builds',
    params: 'sources[], embedModelId, chunkSize',
    response: 'vecId, jobId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'vec.tb_ingest_job, vec.tb_doc_version',
  },
  getAiVectorBuildsByVecId: {
    no: 204, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F08',
    name: '벡터 인덱스 상세', method: 'GET', path: '/api/v1/ai/vector-builds/{vecId}',
    params: '',
    response: 'config{}, stats{}, errors[]',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'vec.tb_ingest_job, vec.tb_ingest_error',
  },
  getAiFinetuneBuilds: {
    no: 205, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F07',
    name: '파인튜닝 체크포인트 목록', method: 'GET', path: '/api/v1/ai/finetune-builds',
    params: 'state, page, size',
    response: 'items[{ftId,startedAt,duration,state,baseModel,method,samples,epoch,vram,eval{intent,cite,refuse,halluc}}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_model_asset',
  },
  postAiFinetuneBuilds: {
    no: 206, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F07',
    name: '파인튜닝 실행', method: 'POST', path: '/api/v1/ai/finetune-builds',
    params: 'baseModel, method, trainsetId, epoch',
    response: 'ftId, jobId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_model_asset, ax.tb_ai_corpus_snapshot',
  },
  getAiFinetuneBuildsByFtId: {
    no: 207, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F08',
    name: '파인튜닝 상세', method: 'GET', path: '/api/v1/ai/finetune-builds/{ftId}',
    params: '',
    response: 'config{}, eval{}, log',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_ai_model_asset',
  },
  getAiModelReleasesPerformanceTrend: {
    no: 208, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F09',
    name: '버전별 성능 추이', method: 'GET', path: '/api/v1/ai/model-releases/performance-trend',
    params: '',
    response: 'labels[], series[{name,data[]}]',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_ai_model_asset, ax.tb_ai_serving_profile',
  },
  getAiModelReleasesDeployLogs: {
    no: 209, domain: '시스템관리', comp: 'SY-11', screen: 'AI 모델 버전 관리', funcId: 'SY-11-F10',
    name: '배포·학습 이력', method: 'GET', path: '/api/v1/ai/model-releases/deploy-logs',
    params: 'page, size',
    response: 'items[{ts,type,detail,by}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_serving_deploy_log',
  },
  getAiAgentsSummary: {
    no: 210, domain: '시스템관리', comp: 'SY-12', screen: 'Agent 실행 현황', funcId: 'SY-12-F01/F04',
    name: 'Agent 요약', method: 'GET', path: '/api/v1/ai/agents/summary',
    params: '',
    response: 'master{state,mode}, activeAgentCnt, eventsPerMin, avgResponseSec',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_agent, ax.tb_ai_agent_run',
    note: '30초 폴링',
  },
  getAiAgents: {
    no: 211, domain: '시스템관리', comp: 'SY-12', screen: 'Agent 실행 현황', funcId: 'SY-12-F01',
    name: 'Agent 목록 조회', method: 'GET', path: '/api/v1/ai/agents',
    params: '',
    response: 'items[{no,agentCd,name,state,lastRunAt,load}]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_agent, ax.tb_ai_agent_run',
    note: '9종',
  },
  getAiAgentsPipeline: {
    no: 212, domain: '시스템관리', comp: 'SY-12', screen: 'Agent 실행 현황', funcId: 'SY-12-F02',
    name: 'Master AI 파이프라인 조회', method: 'GET', path: '/api/v1/ai/agents/pipeline',
    params: '',
    response: 'stages[{stage,name,state,elapsedMs}]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_pipeline_stage',
  },
  postAiAgentsByAgentCdRestart: {
    no: 213, domain: '시스템관리', comp: 'SY-12', screen: 'Agent 실행 현황', funcId: 'SY-12-F03',
    name: 'Agent 재시작', method: 'POST', path: '/api/v1/ai/agents/{agentCd}/restart',
    params: '',
    response: 'success, restartedAt',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_ai_agent, ax.tb_log_audit',
  },
  getAiAgentsByAgentCdRuns: {
    no: 214, domain: '시스템관리', comp: 'SY-12', screen: 'Agent 실행 현황', funcId: 'SY-12-F05',
    name: 'Agent 실행 이력', method: 'GET', path: '/api/v1/ai/agents/{agentCd}/runs',
    params: 'from, to, state, page, size',
    response: 'items[{runId,startedAt,endedAt,state,inputCnt,outputCnt,errorMsg}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_ai_agent_run',
  },
  getMetricsStandardsSummary: {
    no: 215, domain: '시스템관리', comp: 'SY-13', screen: '지표 측정 데이터 관리', funcId: 'SY-13-F03',
    name: '지표 기준 요약', method: 'GET', path: '/api/v1/metrics/standards/summary',
    params: '',
    response: 'totalCnt, appliedCnt, criticalCnt, warnCnt, lastUpdated{at,by}',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_met_metric_std',
  },
  getMetricsStandards: {
    no: 216, domain: '시스템관리', comp: 'SY-13', screen: '지표 측정 데이터 관리', funcId: 'SY-13-F01',
    name: '지표 기준 목록 조회', method: 'GET', path: '/api/v1/metrics/standards',
    params: 'category, applied, level, page, size',
    response: 'items[{stdId,category,name,unit,currentValue,normal,warn,critical,window,basis,level,direction,applied,updatedAt,updatedBy}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_met_metric_std, ax.tb_met_metric_value',
    note: '12종',
  },
  postMetricsStandards: {
    no: 217, domain: '시스템관리', comp: 'SY-13', screen: '지표 측정 데이터 관리', funcId: 'SY-13-F01',
    name: '지표 기준 등록', method: 'POST', path: '/api/v1/metrics/standards',
    params: 'category, name, unit, normal, warn, critical, window, basis, applied, direction',
    response: 'stdId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_met_metric_std',
    note: 'direction = 값이 클수록 나쁨/작을수록 나쁨',
  },
  putMetricsStandardsByStdId: {
    no: 218, domain: '시스템관리', comp: 'SY-13', screen: '지표 측정 데이터 관리', funcId: 'SY-13-F02',
    name: '지표 기준 수치 수정', method: 'PUT', path: '/api/v1/metrics/standards/{stdId}',
    params: 'normal, warn, critical, window, basis, direction',
    response: 'success, level(NORMAL|WARN|CRIT), direction(high|low|null)',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_met_metric_std, ax.tb_met_metric_std_hist',
    note: '저장 시 판정 재계산',
  },
  patchMetricsStandardsByStdIdState: {
    no: 219, domain: '시스템관리', comp: 'SY-13', screen: '지표 측정 데이터 관리', funcId: 'SY-13-F04',
    name: '지표 적용/해제', method: 'PATCH', path: '/api/v1/metrics/standards/{stdId}/state',
    params: 'applied(true|false)',
    response: 'success',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_met_metric_std',
    note: '미적용 지표는 알림·판정에서 제외',
  },
  getMetricsStandardsHistory: {
    no: 220, domain: '시스템관리', comp: 'SY-13', screen: '지표 측정 데이터 관리', funcId: 'SY-13-F05',
    name: '기준 수치 변경 이력', method: 'GET', path: '/api/v1/metrics/standards/history',
    params: 'stdId, page, size',
    response: 'items[{ts,metric,field,before,after,by}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_met_metric_std_hist',
  },
  getMetricsStandardsByStdIdUsage: {
    no: 221, domain: '시스템관리', comp: 'SY-13', screen: '지표 측정 데이터 관리', funcId: 'SY-13-F06',
    name: '기준 수치 사용처 조회', method: 'GET', path: '/api/v1/metrics/standards/{stdId}/usage',
    params: '',
    response: 'alertConditions[], dashboards[], reports[]',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_alm_cond, ax.tb_met_metric_source',
  },
  getDownloadLogsSummary: {
    no: 222, domain: '시스템관리', comp: 'SY-14', screen: '보고서 다운로드 이력', funcId: 'SY-14-F03',
    name: '다운로드 이력 요약', method: 'GET', path: '/api/v1/download-logs/summary',
    params: 'from, to',
    response: 'totalCnt, todayCnt, blindIncludedCnt, topUser{name,cnt}, byReport[], byUser[]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_rpt_download_log, ax.tb_rpt_download_blind',
  },
  getDownloadLogs: {
    no: 223, domain: '시스템관리', comp: 'SY-14', screen: '보고서 다운로드 이력', funcId: 'SY-14-F02',
    name: '다운로드 이력 조회', method: 'GET', path: '/api/v1/download-logs',
    params: 'from, to, reportId, deptId, format, page, size',
    response: 'items[{ts,empNo,name,dept,report,format,scope,rowCnt,blindCnt,ip}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_rpt_download_log',
  },
  postDownloadLogs: {
    no: 224, domain: '시스템관리', comp: 'SY-14', screen: '보고서 다운로드 이력', funcId: 'SY-14-F01',
    name: '다운로드 이력 기록', method: 'POST', path: '/api/v1/download-logs',
    params: 'reportId, reportNm, format, scope, rowCnt, blindCnt',
    response: 'logId',
    roles: '전 부서', blind: [], priority: 1,
    tables: 'ax.tb_rpt_download_log, ax.tb_rpt_download_blind',
    note: '엑셀·CSV·인쇄 모두 기록. 서버 내부 호출 권장',
  },
  getDownloadLogsRetentionPolicy: {
    no: 225, domain: '시스템관리', comp: 'SY-14', screen: '보고서 다운로드 이력', funcId: 'SY-14-F04',
    name: '보존 정책 조회', method: 'GET', path: '/api/v1/download-logs/retention-policy',
    params: '',
    response: 'retentionYears(3), archivedCnt, nextArchiveAt',
    roles: '전산팀·통합관리자', blind: [], priority: 3,
    tables: 'ax.tb_rpt_download_log',
  },
  getSyncJobsSummary: {
    no: 226, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F08',
    name: '연동 요약', method: 'GET', path: '/api/v1/sync/jobs/summary',
    params: 'date',
    response: 'syncState, todayRows, failedRows, failedJobCnt, avgDurationMin, lastBatchAt',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sync_job',
  },
  getSyncJobs: {
    no: 227, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F01',
    name: '이관 작업 이력 조회', method: 'GET', path: '/api/v1/sync/jobs',
    params: 'from, to, srcTable, state, page, size',
    response: 'items[{jobId,srcTable,dstTable,kind,startedAt,endedAt,duration,rows,okRows,ngRows,state}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sync_job',
    note: '30초 폴링(진행 중 작업)',
  },
  getSyncRuns: {
    no: 236.5, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F01',
    name: '엔진 실행 이력', method: 'GET', path: '/api/v1/sync/runs',
    params: 'from, to, state, mode, page, size',
    response: 'items[{runId,mode,modeNm,state,stateNm,startedAt,endedAt,durationSec,triggeredByCd,triggeredBy,options,dryRun,tableCnt,successCnt,failCnt,okRows,ngRows,driftOpenCntAtRun,engineVersion,host,message}], meta',
    roles: '통합관리자·전산팀', blind: [], priority: 1,
    tables: 'ax.tb_sync_run',
    note: 'jobs 는 테이블 1건, runs 는 엔진 1회 실행. 표에 닿지 못한 실행은 jobs 에 안 남습니다',
  },
  getSyncJobsByJobId: {
    no: 228, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F02',
    name: '이관 작업 상세', method: 'GET', path: '/api/v1/sync/jobs/{jobId}',
    params: '',
    response: 'job{}, params{}, errors[{rowNo,message,rawData}]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sync_job, ax.tb_sync_job_error',
  },
  postSyncJobsByJobIdRetry: {
    no: 229, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F03',
    name: '이관 작업 재실행', method: 'POST', path: '/api/v1/sync/jobs/{jobId}/retry',
    params: '',
    response: 'newJobId',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sync_job, ax.tb_log_audit',
    note: '실패 작업만 재실행',
  },
  postSyncJobsManual: {
    no: 230, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F04',
    name: '수동 이관 예약', method: 'POST', path: '/api/v1/sync/jobs/manual',
    params: 'srcTables[], kind(full|incremental), scheduledAt',
    response: 'jobIds[]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sync_job',
  },
  postSyncConnectionTest: {
    no: 231, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F05',
    name: '연결 테스트', method: 'POST', path: '/api/v1/sync/connection-test',
    params: 'target(mssql|postgresql|all)',
    response: 'results[{target,connected,responseMs,version}]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: '',
  },
  getSyncMaps: {
    no: 232, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F06',
    name: '연동 매핑 조회', method: 'GET', path: '/api/v1/sync/maps',
    params: 'srcTable',
    response: 'items[{srcTable,srcColumn,dstSchema,dstTable,dstColumn,transform}]',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sync_map',
  },
  getSyncPolicy: {
    no: 233, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F06',
    name: '연동 정책 조회', method: 'GET', path: '/api/v1/sync/policy',
    params: '',
    response: 'batchCron, incrementalKey, retryPolicy, failAlertCondId, retentionDays',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_sync_job, ax.tb_alm_cond',
  },
  getSyncSchemaDriftSummary: {
    no: 234, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F09',
    name: '스키마 드리프트 요약', method: 'GET', path: '/api/v1/sync/schema-drift/summary',
    params: '',
    response: 'driftState, openCnt, sourceNewCnt, sourceMissingCnt, targetNewCnt, targetMissingCnt, maxDetectCnt, lastCheckedAt',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sync_schema_drift',
    note: '이관 엔진이 배치마다 기록 · API 는 조회만',
  },
  getSyncSchemaDrift: {
    no: 235, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F10',
    name: '스키마 드리프트 목록 조회', method: 'GET', path: '/api/v1/sync/schema-drift',
    params: 'side(SOURCE|TARGET), kind(NEW|MISSING), resolved, page, size',
    response: 'items[{driftId,side,kind,objectName,mapId,detail,firstSeenAt,lastSeenAt,detectCnt,resolved}], meta',
    roles: '전산팀·통합관리자', blind: [], priority: 1,
    tables: 'ax.tb_sync_schema_drift, ax.tb_sync_map',
    note: '이관 정의에 없는 신규 테이블 · 정의에는 있으나 사라진 테이블',
  },
  postSyncSchemaDriftByDriftIdResolve: {
    no: 236, domain: '시스템관리', comp: 'SY-15', screen: '데이터 연동 이력', funcId: 'SY-15-F11',
    name: '스키마 드리프트 해소 처리', method: 'POST', path: '/api/v1/sync/schema-drift/{driftId}/resolve',
    params: 'note',
    response: 'driftId, resolved',
    roles: '전산팀·통합관리자', blind: [], priority: 2,
    tables: 'ax.tb_sync_schema_drift, ax.tb_log_audit',
    note: '원인이 남아 있으면 다음 배치에서 엔진이 다시 연다',
  },
};

/** 전체 API 건수 */
export const ENDPOINT_COUNT = Object.keys(ENDPOINTS).length;

/** 도메인별 엔드포인트 키 목록 */
export function endpointsByDomain(domain) {
  return Object.entries(ENDPOINTS)
    .filter(([, def]) => def.domain === domain)
    .map(([key]) => key);
}

/** 화면(컴포넌트 ID)별 엔드포인트 키 목록 — 화면-API 매핑 확인용 */
export function endpointsByComponent(comp) {
  return Object.entries(ENDPOINTS)
    .filter(([, def]) => def.comp === comp)
    .map(([key]) => key);
}
